#lang ivy1.7

include order
include quic_infer
include file
include quic_shim
# include quic_locale
include random_value

parameter server_addr : ip.addr =  0x0a000001 # 0x7f000001 #
parameter server_port : ip.port = 4443
parameter server_port_alt : ip.port = 4443
parameter server_cid  : cid = 0xb

instance server        : quic_endpoint.server_ep(server_addr,server_port)
instance second_server : quic_endpoint.server_ep(server_addr,server_port_alt) # TODO 
