#lang ivy1.7

include order
include quic_infer
include file
include quic_shim
# include quic_locale
include random_value

parameter victim_addr : ip.addr = 0x0a000401
parameter victim_port : ip.port = 4430
parameter is_victim : bool = false

instance victim_agent : quic_endpoint.victim_ep(victim_addr,victim_port)
 
# An ip endpoint for the client to migrate to. TODO

# a socket for the server

var sock_victim : net.socket

# Open a server socket to listen on and create an instance of TLS.
# TODO: we should have one instance of TLS per connection




