"""
Shared command generation utilities for execution environment plugins.

This module provides reusable utilities to eliminate code duplication in
execution environment plugin command generation, including:
- Common command building patterns
- Output file management
- Wrapper command generation
- Command processing and application
"""

import hashlib
import logging
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from panther.config.core.models import ProtocolRole
from panther.core.command_processor.builders import ServiceCommandBuilder
from panther.core.command_processor.utils.summarizer import CommandSummarizer
from panther.plugins.services.services_interface import IServiceManager


@dataclass
class OutputFileSpec:
    """Specification for an output file to be generated by an execution environment."""

    file_type: str  # Type identifier (e.g., "profile", "trace", "summary")
    file_path: str  # Full path to the output file
    service_name: str  # Name of the service this file belongs to
    description: Optional[str] = None  # Human-readable description
    is_primary: bool = True  # Whether this is a primary output (vs auxiliary)


@dataclass
class WrapperCommandSpec:
    """Specification for generating wrapper commands."""

    environment_name: str  # Name of the execution environment
    service_name: str  # Name of the service being wrapped
    wrapper_setup: str  # Main wrapper setup commands
    pre_run_commands: List[str] = field(
        default_factory=list
    )  # Commands before main execution
    post_run_commands: List[str] = field(
        default_factory=list
    )  # Commands after main execution
    environment_vars: Dict[str, str] = field(
        default_factory=dict
    )  # Environment variables to set
    is_critical: bool = False  # Whether wrapper failure should fail the entire test
    use_wrapper_chaining: bool = True  # Whether to support chaining multiple wrappers


class OutputFileManager:
    """Manages output file path generation and registration for execution environments."""

    def __init__(
        self, register_output_callback, logger: Optional[logging.Logger] = None
    ):
        """
        Initialize the output file manager.

        Args:
            register_output_callback: Callback function to register output files
            logger: Optional logger instance
        """
        self.register_output_callback = register_output_callback
        self.logger = logger or logging.getLogger(__name__)
        self._registered_files: List[OutputFileSpec] = []

    def generate_output_path(
        self,
        service_name: str,
        file_type: str,
        timestamp: str,
        extension: str,
        base_dir: str = "/app/logs",
    ) -> str:
        """
        Generate a standardized output file path.

        Args:
            service_name: Name of the service
            file_type: Type of output file (e.g., 'profile', 'trace')
            timestamp: Timestamp for this execution
            extension: File extension (without dot)
            base_dir: Base directory for output files

        Returns:
            str: Full path to the output file
        """
        filename = f"{service_name}_{file_type}_{timestamp}.{extension}"
        return f"{base_dir}/{filename}"

    def register_output_file(
        self,
        file_type: str,
        file_path: str,
        service_name: str,
        description: Optional[str] = None,
        is_primary: bool = True,
    ) -> OutputFileSpec:
        """
        Register an output file with the environment.

        Args:
            file_type: Type identifier for the file
            file_path: Full path to the output file
            service_name: Name of the service this file belongs to
            description: Optional description of the file
            is_primary: Whether this is a primary output file

        Returns:
            OutputFileSpec: The registered file specification
        """
        spec = OutputFileSpec(
            file_type=file_type,
            file_path=file_path,
            service_name=service_name,
            description=description,
            is_primary=is_primary,
        )

        # Register with the execution environment
        self.register_output_callback(file_type, file_path, service_name)
        self._registered_files.append(spec)

        self.logger.debug(
            "Registered output file: %s -> %s (%s)", file_type, file_path, service_name
        )

        return spec

    def get_registered_files(
        self, service_name: Optional[str] = None
    ) -> List[OutputFileSpec]:
        """
        Get all registered output files, optionally filtered by service.

        Args:
            service_name: Optional service name to filter by

        Returns:
            List[OutputFileSpec]: List of registered file specifications
        """
        if service_name:
            return [f for f in self._registered_files if f.service_name == service_name]
        return self._registered_files.copy()


class WrapperCommandGenerator:
    """Generates common wrapper command patterns for execution environments."""

    def __init__(self, logger: Optional[logging.Logger] = None):
        """
        Initialize the wrapper command generator.

        Args:
            logger: Optional logger instance
        """
        self.logger = logger or logging.getLogger(__name__)

    def generate_environment_wrapper(
        self,
        environment_name: str,
        wrapper_command: str,
        service_name: str,
        additional_env_vars: Optional[Dict[str, str]] = None,
    ) -> str:
        """
        Generate a standard environment wrapper setup command.

        Args:
            environment_name: Name of the execution environment
            wrapper_command: The wrapper command to set up
            service_name: Name of the service being wrapped
            additional_env_vars: Optional additional environment variables

        Returns:
            str: Multi-line wrapper setup command
        """
        env_vars_setup = ""
        if additional_env_vars:
            env_vars_lines = [
                f"export {key}={value}" for key, value in additional_env_vars.items()
            ]
            env_vars_setup = "\n".join(env_vars_lines) + "\n"

        return f"""
# Setup {environment_name} wrapper for {service_name}
{env_vars_setup}# Execute wrapper command directly instead of writing to file
# This prevents wrapper file content concatenation issues
echo "Executing {environment_name} wrapper for {service_name}" >> /app/logs/{service_name}_exec_env_setup.log
{wrapper_command}
echo "Completed {environment_name} wrapper for {service_name}" >> /app/logs/{service_name}_exec_env_setup.log
""".strip()

    def generate_conditional_wrapper(
        self,
        condition: str,
        environment_name: str,
        wrapper_command: str,
        service_name: str,
        fallback_message: Optional[str] = None,
    ) -> str:
        """
        Generate a conditional wrapper setup command.

        Args:
            condition: Shell condition for wrapper setup
            environment_name: Name of the execution environment
            wrapper_command: The wrapper command to set up
            service_name: Name of the service being wrapped
            fallback_message: Optional message when condition fails

        Returns:
            str: Multi-line conditional wrapper command
        """
        fallback = ""
        if fallback_message:
            fallback = f"""
else
    echo "{fallback_message}" >> /app/logs/{service_name}_exec_env_setup.log"""

        return f"""
# Conditional {environment_name} wrapper setup for {service_name}
if {condition}; then
    {self.generate_environment_wrapper(environment_name, wrapper_command, service_name)}{fallback}
fi
""".strip()

    def generate_post_processing_command(
        self,
        input_file: str,
        output_file: str,
        processing_command: str,
        service_name: str,
        description: str,
        error_message: Optional[str] = None,
    ) -> str:
        """
        Generate a standard post-processing command.

        Args:
            input_file: Path to input file to process
            output_file: Path to output file to generate
            processing_command: Command to process the input file
            service_name: Name of the service
            description: Description of the processing
            error_message: Optional custom error message

        Returns:
            str: Multi-line post-processing command
        """
        error_msg = error_message or f"Failed to generate {description}"

        return f"""
# {description} for {service_name}
if [ -f "{input_file}" ]; then
    {processing_command} || echo "{error_msg}" >> /app/logs/{service_name}_exec_env_setup.log
    echo "Generated {description}: {output_file}" >> /app/logs/{service_name}_exec_env_setup.log
else
    echo "Input file not found: {input_file}" >> /app/logs/{service_name}_exec_env_setup.log
fi
""".strip()


class ExecutionEnvironmentCommandBuilder:
    """
    High-level command builder for execution environments.

    This class wraps ServiceCommandBuilder with execution environment-specific
    patterns and provides common command generation utilities.
    """

    def __init__(
        self,
        service: IServiceManager,
        environment_name: str,
        timestamp: str,
        output_file_manager: OutputFileManager,
        wrapper_generator: WrapperCommandGenerator,
        logger: Optional[logging.Logger] = None,
    ):
        """
        Initialize the execution environment command builder.

        Args:
            service: The service manager to build commands for
            environment_name: Name of the execution environment
            timestamp: Timestamp for this execution
            output_file_manager: Manager for output files
            wrapper_generator: Generator for wrapper commands
            logger: Optional logger instance
        """
        self.service = service
        self.environment_name = environment_name
        self.timestamp = timestamp
        self.output_file_manager = output_file_manager
        self.wrapper_generator = wrapper_generator
        self.logger = logger or logging.getLogger(__name__)

        # Get service info
        self.service_name = getattr(service, "service_name", service.__class__.__name__)
        self.service_role = getattr(service, "role", ProtocolRole.SERVER)

        # Create underlying command builder
        self.command_builder = ServiceCommandBuilder(self.service_role)

        # Track generated commands
        self._wrapper_commands: List[str] = []
        self._post_run_commands: List[str] = []
        # Track applied wrappers to prevent duplicates
        self._applied_wrappers: set = set()

    def add_wrapper_command(
        self,
        wrapper_command: str,
        description: Optional[str] = None,
        additional_env_vars: Optional[Dict[str, str]] = None,
        is_critical: bool = False,
        setup_commands: Optional[List[str]] = None,
        main_command_wrapper: Optional[str] = None,
    ) -> "ExecutionEnvironmentCommandBuilder":
        """
        Add a wrapper command for the execution environment.

        Args:
            wrapper_command: The wrapper command to add (legacy - for backward compatibility)
            description: Optional description of the wrapper
            additional_env_vars: Optional additional environment variables
            is_critical: Whether this wrapper is critical for the test
            setup_commands: Optional list of setup commands to run before main command
            main_command_wrapper: Optional wrapper to apply to main command (e.g., "strace -o file.log")

        Returns:
            ExecutionEnvironmentCommandBuilder: Self for method chaining
        """
        # Create command fingerprint for deduplication
        command_fingerprint = hashlib.md5(
            f"{self.environment_name}:{wrapper_command}:{str(additional_env_vars)}:{str(setup_commands)}:{main_command_wrapper}".encode()
        ).hexdigest()

        # Check if this wrapper command has already been applied
        if command_fingerprint in self._applied_wrappers:
            self.logger.debug(
                "Skipping duplicate wrapper command for %s: %s",
                self.service_name,
                (
                    f"{wrapper_command[:50]}..."
                    if len(wrapper_command) > 50
                    else wrapper_command
                ),
            )
            return self

        # Mark this wrapper as applied
        self._applied_wrappers.add(command_fingerprint)

        # Handle new architecture: setup commands + main command wrapper
        if setup_commands or main_command_wrapper:
            # Add setup commands to pre_run_cmds if provided
            if setup_commands:
                for i, setup_cmd in enumerate(setup_commands):
                    self.command_builder.add_command(
                        command=setup_cmd,
                        description=f"{description or self.environment_name} setup {i+1}",
                        is_multiline=True,
                        is_critical=is_critical,
                        environment=additional_env_vars or {},
                    )
                    self._wrapper_commands.append(setup_cmd)

            # Write main command wrapper to wrapper file if provided
            if main_command_wrapper:
                wrapper_file_command = self._generate_wrapper_file_command(
                    main_command_wrapper
                )
                self.command_builder.add_command(
                    command=wrapper_file_command,
                    description=f"Write {self.environment_name} wrapper to file",
                    is_multiline=True,
                    is_critical=is_critical,
                    environment=additional_env_vars or {},
                )
                self._wrapper_commands.append(wrapper_file_command)

        else:
            # Legacy approach: treat wrapper_command as setup command
            wrapper_setup = self.wrapper_generator.generate_environment_wrapper(
                self.environment_name,
                wrapper_command,
                self.service_name,
                additional_env_vars,
            )

            self.command_builder.add_command(
                command=wrapper_setup,
                description=description
                or f"Setup {self.environment_name} wrapper for {self.service_name}",
                is_multiline=True,
                is_critical=is_critical,
                environment=additional_env_vars or {},
            )

            self._wrapper_commands.append(wrapper_setup)

        # Use smart command summarization for logging
        if main_command_wrapper:
            self.logger.debug(
                "Added wrapper for %s: setup commands + main wrapper: %s",
                self.service_name,
                main_command_wrapper,
            )
        else:
            command_summary = CommandSummarizer.summarize_single_command(
                wrapper_command
            )
            self.logger.debug(
                "Added wrapper command for %s: %s", self.service_name, command_summary
            )

        return self

    def _generate_wrapper_file_command(self, main_command_wrapper: str) -> str:
        """
        Generate a command to write the main command wrapper to the wrapper file.

        This command writes the wrapper immediately during setup phase, ensuring
        the wrapper file exists before the entrypoint script tries to read it.

        Args:
            main_command_wrapper: The wrapper command to write to file

        Returns:
            str: Command to write wrapper to file
        """
        wrapper_file = f"/app/logs/{self.service_name}_exec_env_wrappers.txt"

        return f"""
# Write {self.environment_name} wrapper to wrapper file for {self.service_name}
echo "Writing {self.environment_name} wrapper to {wrapper_file}" >> /app/logs/{self.service_name}_exec_env_setup.log
# Use cat with EOF to properly write wrapper content with special characters
cat > {wrapper_file} << 'EOF'
{main_command_wrapper}
EOF
echo "Wrapper file content written:" >> /app/logs/{self.service_name}_exec_env_setup.log
cat {wrapper_file} >> /app/logs/{self.service_name}_exec_env_setup.log 2>/dev/null || echo "Failed to read wrapper file" >> /app/logs/{self.service_name}_exec_env_setup.log
# Ensure wrapper file is available for entrypoint script
ls -la {wrapper_file} >> /app/logs/{self.service_name}_exec_env_setup.log 2>/dev/null || echo "Wrapper file not found after creation" >> /app/logs/{self.service_name}_exec_env_setup.log
"""

    def add_conditional_wrapper(
        self,
        condition: str,
        wrapper_command: str,
        description: Optional[str] = None,
        fallback_message: Optional[str] = None,
        is_critical: bool = False,
    ) -> "ExecutionEnvironmentCommandBuilder":
        """
        Add a conditional wrapper command.

        Args:
            condition: Shell condition for wrapper setup
            wrapper_command: The wrapper command to add
            description: Optional description of the wrapper
            fallback_message: Optional message when condition fails
            is_critical: Whether this wrapper is critical for the test

        Returns:
            ExecutionEnvironmentCommandBuilder: Self for method chaining
        """
        conditional_wrapper = self.wrapper_generator.generate_conditional_wrapper(
            condition,
            self.environment_name,
            wrapper_command,
            self.service_name,
            fallback_message,
        )

        self.command_builder.add_command(
            command=conditional_wrapper,
            description=description
            or f"Conditional {self.environment_name} wrapper for {self.service_name}",
            is_multiline=True,
            is_critical=is_critical,
        )

        self._wrapper_commands.append(conditional_wrapper)

        return self

    def add_post_processing(
        self,
        input_file: str,
        output_file: str,
        processing_command: str,
        description: str,
        file_type: Optional[str] = None,
        error_message: Optional[str] = None,
    ) -> "ExecutionEnvironmentCommandBuilder":
        """
        Add a post-processing command.

        Args:
            input_file: Path to input file to process
            output_file: Path to output file to generate
            processing_command: Command to process the input file
            description: Description of the processing
            file_type: Optional file type for output registration
            error_message: Optional custom error message

        Returns:
            ExecutionEnvironmentCommandBuilder: Self for method chaining
        """
        post_process_cmd = self.wrapper_generator.generate_post_processing_command(
            input_file,
            output_file,
            processing_command,
            self.service_name,
            description,
            error_message,
        )

        self.command_builder.add_command(
            command=post_process_cmd,
            description=f"Post-process {description} for {self.service_name}",
            is_multiline=True,
            is_critical=False,
        )

        self._post_run_commands.append(post_process_cmd)

        # Register output file if file_type is provided
        if file_type:
            self.output_file_manager.register_output_file(
                file_type, output_file, self.service_name, description, is_primary=False
            )

        return self

    def register_output_file(
        self,
        file_type: str,
        extension: str,
        description: Optional[str] = None,
        base_dir: str = "/app/logs",
    ) -> str:
        """
        Register an output file and return its path.

        Args:
            file_type: Type identifier for the file
            extension: File extension (without dot)
            description: Optional description of the file
            base_dir: Base directory for output files

        Returns:
            str: Full path to the registered output file
        """
        file_path = self.output_file_manager.generate_output_path(
            self.service_name, file_type, self.timestamp, extension, base_dir
        )

        self.output_file_manager.register_output_file(
            file_type, file_path, self.service_name, description, is_primary=True
        )

        return file_path

    def build_and_apply(self, command_modifier_callback) -> Dict[str, Any]:
        """
        Build all commands and apply them to the service.

        Args:
            command_modifier_callback: Callback to modify service commands

        Returns:
            Dict[str, Any]: Results of the command application
        """
        # Process all commands
        processed_commands = self.command_builder.process_commands()
        self.logger.debug(
            "Processing commands for service %s in environment %s: %s",
            self.service_name,
            self.environment_name,
            processed_commands,
        )
        if not processed_commands:
            self.logger.warning(
                "No commands were processed for service %s", self.service_name
            )
            return {}

        # Separate wrapper and post-processing commands
        wrapper_commands = []
        post_run_commands = []

        for i, cmd_dict in enumerate(processed_commands):
            command_str = (
                cmd_dict["command"] if isinstance(cmd_dict, dict) else str(cmd_dict)
            )

            if i < len(self._wrapper_commands):
                wrapper_commands.append(command_str)
            else:
                post_run_commands.append(command_str)

        results = {}

        self.logger.debug(
            "Applying commands for service %s in environment %s: %s",
            self.service_name,
            self.environment_name,
            processed_commands,
        )

        self.logger.debug(
            "Wrapper commands: %s, Post-run commands: %s",
            wrapper_commands,
            post_run_commands,
        )

        # Apply wrapper commands
        if wrapper_commands:
            wrapper_result = command_modifier_callback(
                self.service,
                f"{self.environment_name}_wrapper",
                {"pre_run_cmds": wrapper_commands},
            )
            results["wrapper_modifications"] = wrapper_result

            # Use command summarization for wrapper application
            wrapper_summary = CommandSummarizer.summarize_command_list(
                wrapper_commands, max_commands=2
            )
            self.logger.info(
                "Applied %s wrapper to service %s: %s",
                self.environment_name,
                self.service_name,
                wrapper_summary,
            )

        # Apply post-processing commands
        if post_run_commands:
            post_result = command_modifier_callback(
                self.service,
                f"{self.environment_name}_post_processing",
                {"post_run_cmds": post_run_commands},
            )
            results["post_processing_modifications"] = post_result

            # Use command summarization for post-processing
            post_summary = CommandSummarizer.summarize_command_list(
                post_run_commands, max_commands=2
            )
            self.logger.info(
                "Applied %s post-processing to service %s: %s",
                self.environment_name,
                self.service_name,
                post_summary,
            )

        # Mark environment as enabled
        if not hasattr(self.service, "environments"):
            self.service.environments = {}
        self.service.environments[self.environment_name.upper()] = True

        self.logger.debug(
            "Service commands after %s modification: %s",
            self.environment_name,
            self.service.run_cmd,
        )

        return results


class CommandGenerationUtilsFactory:
    """Factory for creating command generation utilities with consistent configuration."""

    @staticmethod
    def create_output_file_manager(
        register_output_callback, logger: Optional[logging.Logger] = None
    ) -> OutputFileManager:
        """Create an OutputFileManager instance."""
        return OutputFileManager(register_output_callback, logger)

    @staticmethod
    def create_wrapper_generator(
        logger: Optional[logging.Logger] = None,
    ) -> WrapperCommandGenerator:
        """Create a WrapperCommandGenerator instance."""
        return WrapperCommandGenerator(logger)

    @staticmethod
    def create_command_builder(
        service: IServiceManager,
        environment_name: str,
        timestamp: str,
        register_output_callback,
        logger: Optional[logging.Logger] = None,
    ) -> ExecutionEnvironmentCommandBuilder:
        """
        Create a complete ExecutionEnvironmentCommandBuilder with all utilities.

        Args:
            service: The service manager to build commands for
            environment_name: Name of the execution environment
            timestamp: Timestamp for this execution
            register_output_callback: Callback to register output files
            logger: Optional logger instance

        Returns:
            ExecutionEnvironmentCommandBuilder: Configured command builder
        """
        output_manager = CommandGenerationUtilsFactory.create_output_file_manager(
            register_output_callback, logger
        )
        wrapper_generator = CommandGenerationUtilsFactory.create_wrapper_generator(
            logger
        )

        return ExecutionEnvironmentCommandBuilder(
            service,
            environment_name,
            timestamp,
            output_manager,
            wrapper_generator,
            logger,
        )


# Convenience function for quick setup
def create_execution_environment_builder(
    service: IServiceManager,
    environment_name: str,
    timestamp: str,
    register_output_callback,
    logger: Optional[logging.Logger] = None,
) -> ExecutionEnvironmentCommandBuilder:
    """
    Convenience function to create an ExecutionEnvironmentCommandBuilder.

    Args:
        service: The service manager to build commands for
        environment_name: Name of the execution environment
        timestamp: Timestamp for this execution
        register_output_callback: Callback to register output files
        logger: Optional logger instance

    Returns:
        ExecutionEnvironmentCommandBuilder: Configured command builder
    """
    return CommandGenerationUtilsFactory.create_command_builder(
        service, environment_name, timestamp, register_output_callback, logger
    )
