"""
Output Collector Interface

This module defines the interface for collecting outputs from execution environments.
"""

from abc import ABC, abstractmethod
from typing import Any


class IOutputCollector(ABC):
    """
    Interface for collecting outputs from execution environments.

    This interface must be implemented by execution environment plugins
    to enable output collection for tester analysis.
    """

    @abstractmethod
    def collect_outputs(self) -> dict[str, str]:
        """
        Collect all outputs generated by this execution environment.

        Returns:
            dict[str, str]: Dictionary mapping output type to file path
                           Example: {
                               "trace": "/path/to/trace.out",
                               "profile": "/path/to/profile.data",
                               "log": "/path/to/execution.log"
                           }
        """
        pass

    @abstractmethod
    def get_output_metadata(self) -> dict[str, Any]:
        """
        Get metadata about the collected outputs.

        Returns:
            dict[str, Any]: Metadata including size, format, timestamp, etc.
                           Example: {
                               "trace": {
                                   "size_bytes": 1024000,
                                   "format": "strace",
                                   "timestamp": "2024-01-01T12:00:00"
                               }
                           }
        """
        pass
