FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
RUN ln -fs /usr/share/zoneinfo/UTC /etc/localtime && \
    apt-get update && \
    apt-get install -y build-essential git cmake software-properties-common \
    openssl libssl-dev pkg-config clang python3 net-tools tcpdump

# https://github.com/gperftools/gperftools
RUN git clone https://github.com/gperftools/gperftools
WORKDIR /gperftools
RUN ./autogen.sh
RUN ./configure
RUN make
RUN sudo make install


RUN apt-get install -y libunwind-dev google-perftools graphviz gv # gperf

WORKDIR /