export default [
    {
        files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx", "**/*.mjs", "**/*.cjs", "**/*.vue"],
        rules: {
          "valid-typeof": ["error", {"requireStringLiterals": false}],
          "use-isnan": ["error", {"enforceForSwitchCase": true, "enforceForIndexOf": false}],
          "require-yield": ["error"],
          "no-with": ["error"],
          "no-useless-escape": ["error"],
          "no-useless-catch": ["error"],
          "no-useless-backreference": ["error"],
          "no-unused-vars": ["error"],
          "no-unused-labels": ["error"],
          "no-unsafe-optional-chaining": ["error", {"disallowArithmeticOperators": false}],
          "no-unsafe-negation": ["error", {"enforceForOrderingRelations": false}],
          "no-unsafe-finally": ["error"],
          "no-unreachable": ["error"],
          "no-unexpected-multiline": ["error"],
          "no-undef": ["error", {"typeof": false}],
          "no-this-before-super": ["error"],
          "no-sparse-arrays": ["error"],
          "no-shadow-restricted-names": ["error"],
          "no-setter-return": ["error"],
          "no-self-assign": ["error", {"props": true}],
          "no-regex-spaces": ["error"],
          "no-redeclare": ["error", {"builtinGlobals": true}],
          "no-prototype-builtins": ["error"],
          "no-octal": ["error"],
          "no-obj-calls": ["error"],
          "no-nonoctal-decimal-escape": ["error"],
          "no-new-symbol": ["error"],
          "no-misleading-character-class": ["error"],
          "no-loss-of-precision": ["error"],
          "no-irregular-whitespace": ["error", {"skipTemplates": false, "skipRegExps": false, "skipComments": false, "skipJSXText": false, "skipStrings": true}],
          "no-invalid-regexp": ["error"],
          "no-inner-declarations": ["error", "functions"],
          "no-import-assign": ["error"],
          "no-global-assign": ["error"],
          "no-func-assign": ["error"],
          "no-fallthrough": ["error", {"allowEmptyCase": false}],
          "no-extra-boolean-cast": ["error", {"enforceForLogicalOperands": false}],
          "no-ex-assign": ["error"],
          "no-empty-pattern": ["error", {"allowObjectPatternsAsParameters": false}],
          "no-empty-character-class": ["error"],
          "no-empty": ["error", {"allowEmptyCatch": false}],
          "no-duplicate-case": ["error"],
          "no-dupe-keys": ["error"],
          "no-dupe-else-if": ["error"],
          "no-dupe-class-members": ["error"],
          "no-dupe-args": ["error"],
          "no-delete-var": ["error"],
          "no-debugger": ["error"],
          "no-control-regex": ["error"],
          "no-constant-condition": ["error", {"checkLoops": true}],
          "no-const-assign": ["error"],
          "no-cond-assign": ["error", "except-parens"],
          "no-compare-neg-zero": ["error"],
          "no-class-assign": ["error"],
          "no-case-declarations": ["error"],
          "no-async-promise-executor": ["error"],
          "getter-return": ["error", {"allowImplicit": false}],
          "for-direction": ["error"],
          "constructor-super": ["error"],
        }
    }
];