tools:
    - name: eslint
      languages: [Javascript, TypeScript]
      extensions: [.js, .jsm, .jsx, .mjs, .ts, .tsx, .vue]
      files: []
    - name: lizard
      languages: [C, CPP, CSharp, Javascript, Python, Ruby, TypeScript]
      extensions: [.c, .cc, .cpp, .cs, .cxx, .gemspec, .h, .hpp, .ino, .jbuilder, .js, .jsm, .jsx, .mjs, .opal, .podspec, .py, .rake, .rb, .ts, .tsx, .vue]
      files: []
    - name: pmd
      languages: [Javascript]
      extensions: [.js, .jsm, .jsx, .mjs, .vue]
      files: []
    - name: pylint
      languages: [Python]
      extensions: [.py]
      files: []
    - name: semgrep
      languages: [C, CPP, CSharp, Dockerfile, Javascript, Python, Ruby, Shell, TypeScript, YAML]
      extensions: [.bash, .c, .cc, .cpp, .cs, .cxx, .dockerfile, .env, .gemspec, .h, .hpp, .ino, .jbuilder, .js, .jsm, .jsx, .mjs, .opal, .podspec, .py, .rake, .rb, .sh, .ts, .tsx, .vue, .yaml, .yml]
      files: []
    - name: trivy
      languages: [C, CPP, CSharp, Dockerfile, JSON, Javascript, Python, Ruby, TypeScript, YAML]
      extensions: [.c, .cc, .cpp, .cs, .cxx, .dockerfile, .env, .gemspec, .h, .hpp, .ino, .jbuilder, .js, .jsm, .json, .jsx, .mjs, .opal, .podspec, .py, .rake, .rb, .ts, .tsx, .vue, .yaml, .yml]
      files: [.deps.json, .env, .env.dev, .env.development, .env.prod, .env.production, .env.staging, Berksfile, Capfile, Cheffile, Directory.Packages.props, Dockerfile, Fastfile, Gemfile, Gemfile.lock, Guardfile, Packages.props, Pipfile.lock, Podfile, Rakefile, Thorfile, Vagabondfile, Vagrantfile, conan.lock, config.ru, package-lock.json, package.json, packages.config, packages.lock.json, pnpm-lock.yaml, poetry.lock, requirements.txt, uv.lock, yarn.lock]
