logging:
  level: 
    description: "Logging level for the experiment."
    type: str
    default: "DEBUG"
    available_values: ["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"]
  format: 
    description: "Logging format for the experiment."
    type: str
    default: "%(asctime)s [%(levelname)s] - %(module)s - %(message)s"
    available_values: ["%(asctime)s [%(levelname)s] - %(module)s - %(message)s", "%(asctime)s [%(levelname)s] - %(message)s"]

paths:
  output_dir: 
    description: "Output directory for the experiment."
    type: str
    default: "outputs"
  log_dir: 
    description: "Log directory for the experiment."
    type: str
    default: "outputs/logs"
  config_dir: 
    description: "Configuration directory for the experiment."
    type: str
    default: "configs"
  plugin_dir: 
    description: "Plugin directory for the experiment."
    type: str
    default: "plugins"

docker:
  build_docker_image: 
    description: "Whether to build the Docker image for the experiment."
    type: bool
    default: True
  remove_docker_image: 
    description: "Whether to remove the Docker image after the experiment."
    type: bool
    default: True
  remove_docker_container: 
    description: "Whether to remove the Docker container after the experiment."
    type: bool
    default: True
  remove_docker_network: 
    description: "Whether to remove the Docker network after the experiment."
    type: bool
    default: True
  remove_docker_volume: 
    description: "Whether to remove the Docker volume after the experiment."
    type: bool
    default: True


tests:
  description: "List of tests to run in the experiment."
  type: list
  items:
    name: 
      description: "Name of the test."
      type: str
    description: 
      description: "Description of the test."
      type: str
    generate_new_certificates: 
      description: "Whether to generate new certificates for the test."
      type: bool
      default: True
    protocol: 
      required: true
      description: "Protocol(s) to test."
      type: list
      items:
        type: str
    network_environment: 
      required: true
      description: "Network environment plugin name."
      type: str
    execution_environment:
      required: true
      description: "Execution environment plugin name."
      type: list
      items:
        type: str
    debug_environment:
      description: "Debug environment plugin name."
      type: list
      items:
        type: str
    iterations:
      description: "Number of iterations for the test."
      type: int
      default: 1
    services:
      required: true
      description: "Services to run for the test."
      type: object
      fields:
        name:
          description: "Name of the service."
          type: str
        implementation:
          description: "Implementation of the service."
          type: str
        version:
          description: "Version of the service."
          type: str
        role:
          description: "Role of the service."
          type: str
        type:
          description: "Type of the service."
          type: str
        target:
          description: "Target service for the service."
          type: str
        ports:
          description: "Ports for the service."
          type: list
          items:
            type: str
    steps:
      description: "Steps to run for the test."
      type: object
      fields:
        record_pcap:
          description: "Whether to record PCAP during the test."
          type: bool
          default: False
        wait:
          description: "Wait time for the test."
          type: int
          default: 60
    assertions:
      description: "Assertions to run for the test."
      type: list
      items:
        type: object
        fields:
          type:
            description: "Type of assertion."
            type: str
          service:
            description: "Service to assert."
            type: str
          endpoint:
            description: "Endpoint to assert."
            type: str
          expected_status:
            description: "Expected status for the assertion."
            type: int
