# panther_core/config/experiment_config.yaml

tests:
  - name: "QUIC Client-Server Communication Test"
    description: "Verify that the Picoquic client can communicate with the Picoquic server over Docker Compose network."
    protocol: "quic"  # Protocol name should match the folder name in plugins/
    network_environment: "docker_compose"  # Environment plugin name
    execution_environment: None 
    services:
      picoquic_server:
        implementation: "picoquic"
        version: "rfc9000"
        parameters:
          role: "server"
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
      picoquic_client:
        implementation: "picoquic"
        version: "rfc9000"
        parameters:
          role: "client"
          target: "picoquic_server"  # Docker Compose service name
          message: "Hello from Picoquic Client!"
        ports:
          - "5000:5000"  # Example port if needed
          - "8080:8080"  # Health check endpoint
    steps:
      wait:
        duration: 10  # seconds to wait during the test
    assertions:
      - type: "service_responsive"
        service: "picoquic_server"
        endpoint: "8080/health"  # Adjust based on health endpoint
        expected_status: 200
