#lang ivy1.7

include quic_server_test

# relation slept

after init {
    slept := false;
}

before packet_event(src:ip.endpoint,dst:ip.endpoint,pkt:quic_packet) {
    if _generating {
        if last_pkt_num(pkt.src_cid,quic_packet_type.one_rtt)/5 = 1  & conn_total_data(the_cid) > 0 & ~slept {  # 
            var idle_timeout_forced := max_idle_timeout_used;
            var force_packet_retransmission_timeout := max_ack_delay_tp;
            call sleep_event(force_packet_retransmission_timeout);
            call time_api.c_timer.sleep(microseconds_to_milliseconds(force_packet_retransmission_timeout));
            # slept := true;
        }
    } else {
        if last_pkt_num(pkt.src_cid,quic_packet_type.one_rtt)/5 = 1  & conn_total_data(the_cid) > 0 & ~slept {  # 
            var idle_timeout_forced := max_idle_timeout_used;
            var force_packet_retransmission_timeout := max_ack_delay_tp;
            call sleep_event(force_packet_retransmission_timeout);
            call time_api.c_timer.sleep(microseconds_to_milliseconds(force_packet_retransmission_timeout));
            # slept := true;
        }
    }
}

export send_ack_eliciting_handshake_packet
export send_ack_eliciting_initial_packet
export frame.ping.handle