FROM shadow-ivy-picotls:latest

ADD src/implementations/quic-implementations/picoquic-vuln /PFV/implementations/quic-implementations/picoquic-vuln
ADD src/implementations/quic-implementations/picotls /PFV/implementations/quic-implementations/picotls

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /PFV/implementations/quic-implementations/picotls
RUN apt-get install libssl-dev -y
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check
WORKDIR /PFV/implementations/quic-implementations/picoquic-vuln/
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /PFV

