ARG image

FROM $image:latest

WORKDIR /PFV/implementations/minip-implementations

ADD src/implementations/minip-implementations/ping-pong/miniP.h ping-pong/miniP.h
ADD src/implementations/minip-implementations/ping-pong/delay.h ping-pong/delay.h
ADD src/implementations/minip-implementations/ping-pong/miniP_client.c ping-pong/miniP_client.c
ADD src/implementations/minip-implementations/ping-pong/miniP_server_fonctionnel.c ping-pong/miniP_server_fonctionnel.c

RUN cd ping-pong/; gcc miniP_client.c -o miniP_client && gcc miniP_server_fonctionnel.c -o miniP_server

WORKDIR /PFV