ARG image

FROM $image:latest

WORKDIR /PFV/implementations/minip-implementations

ADD src/implementations/minip-implementations/ping-pong-flaky/miniP.h ping-pong-flaky/miniP.h
ADD src/implementations/minip-implementations/ping-pong-flaky/delay.h ping-pong-flaky/delay.h
ADD src/implementations/minip-implementations/ping-pong-flaky/delay_flaky.h ping-pong-flaky/delay_flaky.h
ADD src/implementations/minip-implementations/ping-pong-flaky/miniP_client.c ping-pong-flaky/miniP_client.c
ADD src/implementations/minip-implementations/ping-pong-flaky/miniP_server_flaky.c ping-pong-flaky/miniP_server_flaky.c

RUN cd ping-pong-flaky/; gcc miniP_client.c -o miniP_client && gcc miniP_server_flaky.c -o miniP_server

WORKDIR /PFV