ARG image

FROM $image:latest

WORKDIR /PFV/implementations/minip-implementations

ADD src/implementations/minip-implementations/ping-pong-mt-fail/miniP.h ping-pong-mt-fail/miniP.h
ADD src/implementations/minip-implementations/ping-pong-mt-fail/delay.h ping-pong-mt-fail/delay.h
ADD src/implementations/minip-implementations/ping-pong-mt-fail/delay_fail.h ping-pong-mt-fail/delay_fail.h
ADD src/implementations/minip-implementations/ping-pong-mt-fail/miniP_client.c ping-pong-mt-fail/miniP_client.c
ADD src/implementations/minip-implementations/ping-pong-mt-fail/miniP_server_mt_fail.c ping-pong-mt-fail/miniP_server_mt_fail.c

RUN cd ping-pong-mt-fail/; gcc miniP_client.c -o miniP_client && gcc miniP_server_mt_fail.c -o miniP_server -lpthread

WORKDIR /PFV