FROM shadow-ivy-picotls:latest

ADD src/quic-implementations/picoquic-vuln /tmp/QUIC-FormalVerification/quic-implementations/picoquic-vuln
ADD src/quic-implementations/picotls /tmp/QUIC-FormalVerification/quic-implementations/picotls

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/picotls
RUN apt-get install libssl-dev -y
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check
WORKDIR /tmp/QUIC-FormalVerification/quic-implementations/picoquic-vuln/
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /tmp/QUIC-FormalVerification

