ARG image

FROM $image:latest

WORKDIR /PFV/implementations/minip-implementations

ADD src/implementations/minip-implementations/ping-pong-mt/miniP.h ping-pong-mt/miniP.h
ADD src/implementations/minip-implementations/ping-pong-mt/delay.h ping-pong-mt/delay.h
ADD src/implementations/minip-implementations/ping-pong-mt/miniP_client.c ping-pong-mt/miniP_client.c
ADD src/implementations/minip-implementations/ping-pong-mt/miniP_server_mt_fonctionnel.c ping-pong-mt/miniP_server_mt_fonctionnel.c

RUN cd ping-pong-mt/; gcc miniP_client.c -o miniP_client && gcc miniP_server_mt_fonctionnel.c -o miniP_server -lpthread

WORKDIR /PFV