ARG image

FROM $image:latest

WORKDIR /tmp/QUIC-FormalVerification/quic-implementations

ADD src/quic-implementations/ping-pong/miniP.h ping-pong/miniP.h
ADD src/quic-implementations/ping-pong/delay.h ping-pong/delay.h
ADD src/quic-implementations/ping-pong/delay_flaky.h ping-pong/delay_flaky.h
ADD src/quic-implementations/ping-pong/delay_fail.h ping-pong/delay_fail.h
ADD src/quic-implementations/ping-pong/miniP_client.c ping-pong/miniP_client.c
ADD src/quic-implementations/ping-pong/miniP_server_fail.c ping-pong/miniP_server_fail.c
ADD src/quic-implementations/ping-pong/miniP_server_flaky.c ping-pong/miniP_server_flaky.c
ADD src/quic-implementations/ping-pong/miniP_server_fonctionnel.c ping-pong/miniP_server_fonctionnel.c

RUN cd ping-pong/; gcc miniP_client.c -o miniP_client && gcc miniP_server_flaky.c -o miniP_server

WORKDIR /tmp/QUIC-FormalVerification