ARG image

FROM $image:latest

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app/implementations/quic-implementations/quinn
ENV PATH="/root/.cargo/bin:${PATH}"


RUN git clone https://github.com/quinn-rs/quinn.git .

RUN git checkout bb02a12a8435a7732a1d762783eeacbb7e50418e
# 0.11.2
# 4395b969a69b9e39bef1333e44312bf2548d4e1c
RUN git submodule update --init --recursive
RUN git submodule update --recursive
ADD quinn/0.11.2/lib.rs /app/implementations/quic-implementations/quinn/quinn-proto/src/lib.rs
RUN cargo build --examples
RUN cargo test || true

WORKDIR /app