FROM shadow-ivy-picotls:latest

ADD pfv/pfv_worker/implementations/quic-implementations/picoquic-vuln /app/implementations/quic-implementations/picoquic-vuln
ADD pfv/pfv_worker/implementations/quic-implementations/picotls /app/implementations/quic-implementations/picotls

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /app/implementations/quic-implementations/picotls
RUN apt-get install libssl-dev -y
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check
WORKDIR /app/implementations/quic-implementations/picoquic-vuln/
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /app

