# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "setup.py" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "panther/panther_worker/Dockerfile.ivy_1" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "panther/panther_worke/Dockerfile.ivy_2" # Location of package manifests
    schedule:
      interval: "weekly"

