ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD miniP.h ping-pong-flaky/miniP.h
ADD delay.h ping-pong-flaky/delay.h
ADD delay_flaky.h ping-pong-flaky/delay_flaky.h
ADD miniP_client.c ping-pong-flaky/miniP_client.c
ADD miniP_server_flaky.c ping-pong-flaky/miniP_server_flaky.c

RUN cd ping-pong-flaky/; gcc miniP_client.c -o miniP_client && gcc miniP_server_flaky.c -o miniP_server

WORKDIR /app