#ivy lang1.7

# https://datatracker.ietf.org/doc/html/rfc9204

# QPACK preserves the ordering of field lines within each field section. An encoder MUST emit field representations in the order they appear in the input field section.

# If the dynamic table does not contain enough room for a new entry without evicting other entries, and the entries that would be evicted are not evictable, the encoder MUST NOT insert that entry into the dynamic table (including duplicates of existing entries). In order to avoid this, an encoder that uses the dynamic table has to keep track of each dynamic table entry referenced by each field section until those representations are acknowledged by the decoder; see Section 4.4.1.

action encode_integer(buf:buf, prefix:stream_pos, value:stream_pos, prefix_len: stream_pos) = {

}

action encode_insert(buf:buf, static_name_index: stream_pos, dunamic_name_index: stream_pos, field_line: stream_pos) = {

}

action encode_static_reference(buf:buf, index:stream_pos) = {

}

action encode_dynamic_reference(buf:buf, index:stream_pos, base: stream_pos) = {

}

action encode_literal(buf:buf, static_name:stream_pos, field_line:stream_pos) = {

}

action encode_dynamic_literal(buf:buf, dynamic_name:stream_pos, base: stream_pos, field_line:stream_pos) = {

}

action encode(dynamic_buf:buf, field_section:stream_pos, base:stream_pos) returns (encoded_buffer:buf, pref_stream_buf:buf) = {

}