ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD miniP.h ping-pong/miniP.h
ADD delay.h ping-pong/delay.h
ADD miniP_client.c ping-pong/miniP_client.c
ADD miniP_server_fonctionnel.c ping-pong/miniP_server_fonctionnel.c

RUN cd ping-pong/; gcc miniP_client.c -o miniP_client && gcc miniP_server_fonctionnel.c -o miniP_server

WORKDIR /app