engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
    - Dockerfile*
    - panther/plugins/services/iut/minip/ping_pong/src
    - panther/plugins/services/testers/panther_ivy/scripts
    - panther/plugins/services/testers/panther_ivy/ivy
    - panther/plugins/services/testers/panther_ivy/doc
    - panther/plugins/services/testers/panther_ivy/examples
    - "tests/**/*"
    - "scripts/**/*"
    - "examples/**/*"
    - "docs/**/*"
    - "*.md"
    - "dev/**/*"