---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
ratings:
  paths:
  - "**.py"
exclude_paths:
- Dockerfile*
- panther/plugins/services/iut/minip/ping_pong/src