FROM shadow-ivy-picotls:latest

ADD quic-implementations/quant /QUIC-FormalVerification/quic-implementations/quant

RUN apt remove --fix-missing -y cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-Linux-x86_64.sh  
RUN chmod +x cmake-3.12.4-Linux-x86_64.sh
RUN mkdir /opt/cmake
RUN bash cmake-3.12.4-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
RUN cmake --version

WORKDIR /QUIC-FormalVerification/quic-implementations/quant/
RUN git checkout 9e309c05f79fb6aa3889dcf7df60b550249d2a2a
RUN git submodule update --init --recursive
#COPY ressources/quant/rfc9000/cid.h /QUIC-FormalVerification/quic-implementations/quant/lib/src/cid.h 
# for 16 bytes max
RUN mkdir Debug 
WORKDIR /QUIC-FormalVerification/quic-implementations/quant/Debug
RUN cmake ..
RUN make

WORKDIR /QUIC-FormalVerification

