FROM shadow-ivy-picotls:latest

ADD quic-implementations/picoquic-vuln /QUIC-FormalVerification/quic-implementations/picoquic-vuln
ADD quic-implementations/picotls /QUIC-FormalVerification/quic-implementations/picotls

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /QUIC-FormalVerification/quic-implementations/picotls
RUN apt-get install libssl-dev -y
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check
WORKDIR /QUIC-FormalVerification/quic-implementations/picoquic-vuln/
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /QUIC-FormalVerification

