ARG image

FROM $image-ivy:latest

WORKDIR /

#https://github.com/gperftools/gperftools
RUN git clone https://github.com/gperftools/gperftools
WORKDIR gperftools
RUN ./autogen.sh
RUN ./configure
RUN make
RUN sudo make install


RUN apt-get install -y libunwind-dev google-perftools graphviz gv # gperf
RUN whereis libprofiler
RUN whereis libtcmalloc

WORKDIR /QUIC-FormalVerification