site_name: Panther Documentation
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  # rest of the navigation...
  # defer to gen-files + literate-nav
  - Code Reference: reference/  
  # rest of the navigation...
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
use_directory_urls: false
plugins:
  - search:
      separator: '[\s\-\.]+'
  - same-dir
  - exclude: # NOT WORKING
      glob:
        - '../panther/panther_worker/app/panther-ivy/**'
        - '../panther/outputs/**'
        - '../panther/panther_webapp/app/res/tmp/**'
        - '*.tmp'
        - '*.pdf'
        - '*.gz'
        - '**/setup.py'
      regex:
        - '.*\.(tmp|bin|tar)$'
  - gen-files:
      scripts:
        - resources/gen_ref_pages.py  # Path to the script generating reference pages
  - literate-nav:
      nav_file: reference/SUMMARY.md  # Path to the generated navigation file
  - section-index
  - mkdocstrings:
      default_handler: python
      show_inheritance_diagram: true
      handlers:
        python:
          setup_commands:
            - import sys
            - from pathlib import Path
            - sys.path.append(str(Path('.').resolve()))
          paths:
            - ../panther/panther_webapp/**
            - ../panther/panther_worker/**

