# /pyproject.toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Panther"
version = "0.0.1"
description = "Panther: Secure Communication Platform"
readme = "README.md"
authors = [
    { name = "ElNiak", email = "christophe.crochet.researcher@gmail.com" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]
homepage = "https://github.com/ElNiak/PANTHER"
requires-python = ">=3.6"
dependencies = [
    "omegaconf=*",
    "cerberus=*",
    "jinja2=*",
    "requests=*",
    "PyYAML=*",
    "docker=*",
    "hypothesis=*",
    "pytest=*",
    "termcolor=*",
    "terminal_banner=*"
]
[project.optional-dependencies]
web = [
    "flask=*",
    "flask_session=*",
    "flask_wtf=*",
    "django=*",
    "flask-socketio=*",
    "Flask-Cors==4.0.1",
    "npf-web-extension=*",
    "execnet=*",
    "pexpect=*",
    "chardet=*",
    "gperf=*",
    "pandas=*",
    "scandir=*",
    "ply=*",
    "plantuml=*",
    "pygraphviz=*",
    "scapy=*",
    "importlib_metadata=*",
]

[project.scripts]
panther = "panther_cli:main"
