#lang ivy1.7

include order
include file
include bgp_shim
include ivy_bgp_speaker_behavior

relation slept_bgp

after init { #getsock(bgp_impl_instance.ep.addr)
    getsock(bgp_impl_instance.ep.addr) :=  net.connect(bgp_ivy_instance.bgpid, bgp_impl_instance.bgpid, bgp_impl_instance.ep.addr);
    pend(bgp_impl_instance.ep.addr) := true;
    slept_bgp := false;
}


before bgp_open_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_open_message){
    if _generating {
        
    }
}

before bgp_update_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_update_message){
    if _generating {
        
    }
}

before bgp_keepalive_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_keepalive_message){
    if _generating {
        
    }
}

before bgp_notification_message_event(src:bgp_id,dst:bgp_id,bgp_message:bgp_notification_message){
    if _generating {
        
    }
}

export bgp_header_message_event
export bgp_open_message_event
export bgp_update_message_event
export bgp_keepalive_message_event
export bgp_notification_message_event

export path_attr.origin.handle
export path_attr.as_path.handle
export as_path_event
export as_event

# export speaker_send_event

export action _finalize = {
    
}