"""
Events Module

This module provides a refactored event and state management system for PANTHER.
It organizes events and states by entity type for clearer separation of concerns.
"""

from panther.core.events.base.event_base import BaseEvent, EventType
from panther.core.events.base.state_base import BaseState, StateManager

# Entity-specific imports
from panther.core.events.experiment import (
    ExperimentState,
    ExperimentEvent,
    ExperimentEventEmitter,
    ExperimentInitializedEvent,
    ExperimentPluginLoadingStartedEvent,
    ExperimentPluginLoadingCompletedEvent,
    ExperimentPluginLoadingFailedEvent,
    ExperimentTestCasesInitializedEvent,
    ExperimentExecutionStartedEvent,
    ExperimentExecutionCompletedEvent,
    ExperimentExecutionFailedEvent,
    ExperimentFinishedEarlyEvent,
    ExperimentCompletedEvent,
    ExperimentFailedEvent,
)
from panther.core.events.test import (
    TestState,
    TestEvent,
    TestEventEmitter,
    TestCreatedEvent,
    TestSetupStartedEvent,
    TestSetupCompletedEvent,
    TestSetupFailedEvent,
    TestEnvironmentSetupStartedEvent,
    TestEnvironmentSetupCompletedEvent,
    TestEnvironmentSetupFailedEvent,
    TestDeploymentStartedEvent,
    TestDeploymentCompletedEvent,
    TestDeploymentFailedEvent,
    TestExecutionStartedEvent,
    TestStepStartedEvent,
    TestStepCompletedEvent,
    TestStepFailedEvent,
    TestAssertionsStartedEvent,
    TestAssertionCheckedEvent,
    TestAssertionsCompletedEvent,
    TestAssertionsFailedEvent,
    TestExecutionCompletedEvent,
    TestExecutionFailedEvent,
    TestTeardownStartedEvent,
    TestTeardownCompletedEvent,
    TestCompletedEvent,
    TestFailedEvent,
    TestResultEvent,
    EnhancedResultEvent,
)
from panther.core.events.service import (
    ServiceState,
    ServiceEvent,
    ServiceEventEmitter,
    ServiceCreatedEvent,
    ServicePreparationStartedEvent,
    ServicePreparationCompletedEvent,
    ServicePreparationFailedEvent,
    ServiceDeploymentStartedEvent,
    ServiceDeploymentCompletedEvent,
    ServiceDeploymentFailedEvent,
    ServiceStartedEvent,
    ServiceReadyEvent,
    ServiceHealthCheckPassedEvent,
    ServiceHealthCheckFailedEvent,
    ServiceStoppedEvent,
    ServiceErrorEvent,
    ServiceDestroyedEvent,
)
from panther.core.events.environment import (
    EnvironmentState,
    EnvironmentEvent,
    EnvironmentEventEmitter,
    EnvironmentCreatedEvent,
    EnvironmentInitializationStartedEvent,
    EnvironmentInitializationCompletedEvent,
    EnvironmentInitializationFailedEvent,
    EnvironmentSetupStartedEvent,
    EnvironmentSetupCompletedEvent,
    EnvironmentSetupFailedEvent,
    EnvironmentReadyEvent,
    EnvironmentTeardownStartedEvent,
    EnvironmentTeardownCompletedEvent,
    EnvironmentTeardownFailedEvent,
    EnvironmentDestroyedEvent,
    EnvironmentErrorEvent,
    EnvironmentResourceEvent,
    EnvironmentConfigurationEvent,
    EnvironmentMonitoringEvent,
    # Network Environment Events
    NetworkEnvironmentEvent,
    NetworkSetupStartedEvent,
    NetworkSetupCompletedEvent,
    NetworkSetupFailedEvent,
    NetworkTeardownStartedEvent,
    NetworkTeardownCompletedEvent,
    # Execution Environment Events
    ExecutionEnvironmentEvent,
    ExecutionEnvironmentSetupStartedEvent,
    ExecutionEnvironmentSetupCompletedEvent,
    ExecutionEnvironmentResourceMonitoringEvent,
    ExecutionEnvironmentLimitExceededEvent,
)
from panther.core.events.metrics import (
    MetricsState,
    MetricsEvent,
    MetricsEventEmitter,
    MetricCollectedEvent,
    ResourceMetricEvent,
    TimingMetricEvent,
    CounterMetricEvent,
    MetricsSummaryEvent,
)
from panther.core.events.step import (
    StepState,
    StepEvent,
    StepEventEmitter,
    StepExecutionStartedEvent,
    StepExecutionCompletedEvent,
    StepExecutionFailedEvent,
    StepProgressEvent,
    StepUnsupportedEvent,
    StepSkippedEvent,
)
from panther.core.events.assertion import (
    AssertionState,
    AssertionEvent,
    AssertionEventEmitter,
    AssertionsValidationStartedEvent,
    AssertionsValidationCompletedEvent,
    AssertionProgressEvent,
    AssertionResultEvent,
    AssertionErrorEvent,
    AssertionUnknownEvent,
)
from panther.core.events.plugin import (
    PluginState,
    PluginEvent,
    PluginEventEmitter,
    PluginLoadingStartedEvent,
    PluginLoadingCompletedEvent,
    PluginLoadingFailedEvent,
    PluginInitializedEvent,
    PluginStartedEvent,
    PluginStoppedEvent,
    PluginErrorEvent,
    PluginServiceCreatedEvent,
    PluginServiceStartedEvent,
    PluginServiceStoppedEvent,
)

__all__ = [
    # Base classes
    "BaseEvent",
    "EventType",
    "BaseState",
    "StateManager",
    # Experiment
    "ExperimentState",
    "ExperimentEvent",
    "ExperimentEventEmitter",
    # Test
    "TestState",
    "TestEvent",
    "TestEventEmitter",
    "TestCreatedEvent",
    "TestSetupStartedEvent",
    "TestSetupCompletedEvent",
    "TestSetupFailedEvent",
    "TestEnvironmentSetupStartedEvent",
    "TestEnvironmentSetupCompletedEvent",
    "TestEnvironmentSetupFailedEvent",
    "TestDeploymentStartedEvent",
    "TestDeploymentCompletedEvent",
    "TestDeploymentFailedEvent",
    "TestExecutionStartedEvent",
    "TestStepStartedEvent",
    "TestStepCompletedEvent",
    "TestStepFailedEvent",
    "TestAssertionsStartedEvent",
    "TestAssertionCheckedEvent",
    "TestAssertionsCompletedEvent",
    "TestAssertionsFailedEvent",
    "TestExecutionCompletedEvent",
    "TestExecutionFailedEvent",
    "TestTeardownStartedEvent",
    "TestTeardownCompletedEvent",
    "TestCompletedEvent",
    "TestFailedEvent",
    "TestResultEvent",
    "EnhancedResultEvent",
    # Service
    "ServiceState",
    "ServiceEvent",
    "ServiceEventEmitter",
    "ServiceCreatedEvent",
    "ServicePreparationStartedEvent",
    "ServicePreparationCompletedEvent",
    "ServicePreparationFailedEvent",
    "ServiceDeploymentStartedEvent",
    "ServiceDeploymentCompletedEvent",
    "ServiceDeploymentFailedEvent",
    "ServiceStartedEvent",
    "ServiceReadyEvent",
    "ServiceHealthCheckPassedEvent",
    "ServiceHealthCheckFailedEvent",
    "ServiceStoppedEvent",
    "ServiceErrorEvent",
    "ServiceDestroyedEvent",
    # Environment
    "EnvironmentState",
    "EnvironmentEvent",
    "EnvironmentEventEmitter",
    "EnvironmentCreatedEvent",
    "EnvironmentInitializationStartedEvent",
    "EnvironmentInitializationCompletedEvent",
    "EnvironmentInitializationFailedEvent",
    "EnvironmentSetupStartedEvent",
    "EnvironmentSetupCompletedEvent",
    "EnvironmentSetupFailedEvent",
    "EnvironmentReadyEvent",
    "EnvironmentTeardownStartedEvent",
    "EnvironmentTeardownCompletedEvent",
    "EnvironmentTeardownFailedEvent",
    "EnvironmentDestroyedEvent",
    "EnvironmentErrorEvent",
    "EnvironmentResourceEvent",
    "EnvironmentConfigurationEvent",
    "EnvironmentMonitoringEvent",
    # Network Environment
    "NetworkEnvironmentEvent",
    "NetworkSetupStartedEvent",
    "NetworkSetupCompletedEvent",
    "NetworkSetupFailedEvent",
    "NetworkTeardownStartedEvent",
    "NetworkTeardownCompletedEvent",
    # Execution Environment
    "ExecutionEnvironmentEvent",
    "ExecutionEnvironmentSetupStartedEvent",
    "ExecutionEnvironmentSetupCompletedEvent",
    "ExecutionEnvironmentResourceMonitoringEvent",
    "ExecutionEnvironmentLimitExceededEvent",
    # Metrics
    "MetricsState",
    "MetricsEvent",
    "MetricsEventEmitter",
    "MetricCollectedEvent",
    "ResourceMetricEvent",
    "TimingMetricEvent",
    "CounterMetricEvent",
    "MetricsSummaryEvent",
    # Step
    "StepState",
    "StepEvent",
    "StepEventEmitter",
    "StepExecutionStartedEvent",
    "StepExecutionCompletedEvent",
    "StepExecutionFailedEvent",
    "StepProgressEvent",
    "StepUnsupportedEvent",
    "StepSkippedEvent",
    # Assertion
    "AssertionState",
    "AssertionEvent",
    "AssertionEventEmitter",
    "AssertionsValidationStartedEvent",
    "AssertionsValidationCompletedEvent",
    "AssertionProgressEvent",
    "AssertionResultEvent",
    "AssertionErrorEvent",
    "AssertionUnknownEvent",
    # Plugin
    "PluginState",
    "PluginEvent",
    "PluginEventEmitter",
    "PluginLoadingStartedEvent",
    "PluginLoadingCompletedEvent",
    "PluginLoadingFailedEvent",
    "PluginInitializedEvent",
    "PluginStartedEvent",
    "PluginStoppedEvent",
    "PluginErrorEvent",
    "PluginServiceCreatedEvent",
    "PluginServiceStartedEvent",
    "PluginServiceStoppedEvent",
]
