FROM localhost_single_container_v1_panther:latest AS localhost_base

{% for service_name, service in services.items() %}

{% if service.type == "tester" %}
FROM {{ service.implementation }}_{{ service.protocol.version }}_panther:latest AS {{ service_name }}_stage
{% else %}
FROM {{ service.implementation }}_{{ service.version }}_panther:latest AS {{ service_name }}_stage
{% endif %}

# Copy files from the service stage to /opt in the final image
{% for port in service.ports %}
EXPOSE {{ port }}
{% endfor %}# Set container working directory
# WORKDIR "{{ deployment_info[service_name]['working_dir'] }}"

# Add service-specific environment variables
ENV ROLE="{{ service.role }}"
ENV UID=${UID}
ENV GID=${GID}
{% if "environment" in deployment_info[service_name] %}
{% for key, value in deployment_info[service_name]["environment"].items() %}
ENV {{ key }}="{{ value }}"
{% endfor %}
{% endif %}

# # Copy logs and volumes
# VOLUME {{ log_dir | realpath }}/{{ service_name  }}:/app/logs
# {% for volume in deployment_info[service_name]['volumes'] %}
# {% if volume | is_dict %}
# VOLUME "{{ volume.local | realpath }}:{{ volume.container }}"
# {% else %}
# VOLUME "{{ volume }}"
# {% endif %}
# {% endfor %}

# Define the command for the service
# TODO manage that in the Ivy module
{% if "ivy" in service_name %}
RUN <<EOF
{{deployment_info[service_name]["compilation_command"]}}
EOF
{% endif %}

{% endfor %}


# Final stage
FROM localhost_single_container_v1_panther:latest
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root

# TODO try to install the packages in the base image and keep them in the final image
RUN apt-get update && \
    apt-get install -y build-essential git cmake software-properties-common \
    openssl libssl-dev pkg-config clang python3 net-tools tcpdump \
    apt-utils  wireshark tshark  libcap2-bin traceroute \
    iputils-ping iproute2 iperf3 netcat-openbsd curl dnsutils iperf 
RUN yes yes | DEBIAN_FRONTEND=teletype dpkg-reconfigure wireshark-common

ARG USER_UID=1000
ARG USER_GID=1000
ARG USER_N=elniak

RUN addgroup --gid ${USER_GID} ${USER_N} && \
    adduser --disabled-password --gecos '' --uid ${USER_UID} --gid ${USER_GID} ${USER_N} && \
    usermod -aG wireshark ${USER_N}


{% for service_name, service in services.items() %}
{% if "ivy" in service_name %}
COPY --from={{ service_name }}_stage /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY --from={{ service_name }}_stage /opt /opt
COPY --from={{ service_name }}_stage /usr/bin /usr/bin
{% else %}
COPY --from={{ service_name }}_stage /opt /opt/{{ service_name }}
{% endif %}
{% endfor %}


ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"

ADD {{ localhost_single_container_config_file }} /run.sh
ENV RUST_BACKTRACE=1
RUN chmod +x /run.sh
ENTRYPOINT [ "/bin/sh", "-c", "./run.sh > /app/logs/localhost_stdout.log 2> /app/logs/localhost_stderr.log" ]

