ARG image

FROM $image:latest

# ADD panther/panther_worker/app/implementations/quic-implementations/picoquic /app/implementations/quic-implementations/picoquic

WORKDIR /app/implementations/quic-implementations/


RUN rm -r /app/implementations/quic-implementations/picotls

RUN cd /app/implementations/quic-implementations/; git clone https://github.com/h2o/picotls.git && cd picotls && git checkout 7d294ab4f2e0ed749b4bcfaf533225a4e0c096f7 && git submodule init && git submodule update && cmake . && make && make check

RUN git clone https://github.com/ElNiak/picoquic.git &&  cd picoquic && git checkout master && /usr/bin/cmake . && make

WORKDIR /app/implementations/minip-implementations

ADD minip/miniP.h ping-pong/miniP.h
ADD minip/delay.h ping-pong/delay.h
ADD minip/miniP_client.c ping-pong/miniP_client.c
ADD minip/miniP_server_fonctionnel.c ping-pong/miniP_server_fonctionnel.c

RUN cd ping-pong/; gcc miniP_client.c -o miniP_client && gcc miniP_server_fonctionnel.c -o miniP_server

WORKDIR /app