#lang ivy1.7

include coap_shim

# Actions for client endpoint
action coap_message_event(src:ip.endpoint, dst:ip.endpoint, request:coap_message) = {
    # current_time := time_api.c_timer.now_millis;
    # call show_current_time(current_time);
    # enough_wait := current_time >= 3000;
    if dst_is_generated(src) {  
        var spkt := msg_serdes.to_bytes(pkt);
        var pkts := prot.arr.empty;
        pkts := pkts.append(spkt);
        call net.send(endpoint_to_pid(src),endpoint_to_socket(src),dst,pkts);
    }
}
