#lang ivy1.7

include order
include ping_file
include ping_shim_server
include ivy_ping_server_behavior

relation slept_ping

after init {
    slept_ping := false;
}

# before pong_event {
#     if _generating {
#         require initial_response;
#     }
# }

before ping_packet_event {
    if ~_generating {
        if ~slept_ping {
            slept_ping := true;
            var timout := time_api.c_timer.sleep_signal(2000);
        }
    }
}

export quic_frame.pong.handle
export quic_frame.timestamp.handle
export ping_packet_event
export client_send_event

export action _finalize = {
    # 
}