#lang ivy1.7

include order
include quic_infer
include file
include ivy_quic_shim_server
include quic_locale
include ivy_quic_server_behavior

#
# We fix the initial transport parameters here. TODO: In principle these
# parameters should be selected randomly by some event.
#

include ivy_quic_server_standard_tp


#
# We fix the initial transport parameters here. TODO: In principle these
# parameters should be selected randomly by some event.
#

# Generate connection_close frames only for the client.

before quic_frameframeframe.connection_closequic_framequic_framequic_frame.connection_close,scid:cid,dcid:cid) {
    if _generating {
        require client.ep.addr ~= 0;         
        require scid = the_cid;
    } else {
        require is_frame_encoding_error
    }
}

# Generate connection_close frames only for the client.

before quic_frameframeframe.application_closequic_framequic_framequic_frame.application_close,scid:cid,dcid:cid) {
    if _generating {
        require client.ep.addr ~= 0;
        require scid = the_cid;
    }
}


before quic_frameframeframe.unknown_framequic_framequic_framequic_frame.unknown_frame,scid:cid,dcid:cid) {
    if _generating {
        require client.ep.addr ~= 0;
        require scid = the_cid;
    }
}

export quic_frameframeframe.ack.handle
export quic_frameframeframe.stream.handle
export quic_frameframeframe.crypto.handle
export quic_frameframeframe.path_response.handle
export quic_frameframeframe.handshake_done.handle
export packet_event
export client_send_event
export tls_recv_event
#export quic_frameframeframe.new_connection_id.handle
#export quic_frameframeframe.retire_connection_id.handle
#export quic_frameframeframe.rst_stream.handle
#export quic_frameframeframe.max_stream_id.handle
#export quic_frameframeframe.connection_close.handle
#export quic_frameframeframe.max_stream_data.handle

#   An endpoint MUST treat the receipt of a quic_frameframeframe of unknown type as a
#   connection error of type FRAME_ENCODING_ERROR.

export quic_frameframeframe.unknown_frame.handle
attribute quic_frameframeframe.unknown_frame.handle.weight = "5"

# TODO connection close 

# Final check
#
# When the test is complete, the tester calls the special action `_finalize`.
# We use this action to make some heuristic checks, for example that some
# data was actually received from the server. We can add advice to this
# action with additional checks.

export action _finalize = {
    # chris TODO 
    require is_frame_encoding_error;
}


