#lang ivy1.7

include quic_client_test

export quic_frame.max_streams.handle
export quic_frame.max_stream_data.handle
export quic_frame.max_data.handle
# export quic_frame.stream_blocked.handle
# export quic_frame.rst_stream.handle
attribute quic_frame.rst_stream.handle.weight = "0.02"
attribute quic_frame.max_streams.handle.weight = "0.02"
attribute quic_frame.max_stream_data.handle.weight = "0.02"
attribute quic_frame.max_data.handle.weight = "0.02"


# export quic_frame.connection_close.handle
# attribute quic_frame.connection_close.handle.weight = "0.02"

#export quic_frame.application_close.handle
#attribute quic_frame.application_close.handle.weight = "0.02"

# export quic_frame.stop_sending.handle

before quic_frame.max_stream_data.handle(f:quic_frame.max_stream_data,scid:cid,dcid:cid,e:quic_packet_type,seq:pkt_num) {
    if _generating {
        require f.pos = 320 | f.pos = 160;
    }
}

before quic_frame.stream_data_blocked.handle(f:quic_frame.stream_data_blocked,scid:cid,dcid:cid,e:quic_packet_type,seq:pkt_num) {
    if _generating {
        require f.pos > 32;
    }
}

before quic_frame.max_data.handle(f:quic_frame.max_data,scid:cid,dcid:cid,e:quic_packet_type,seq:pkt_num) {
    if _generating {
        require f.pos = 2048 | f.pos = 40;
    }
}
