#lang ivy1.7

include quic_client_test

#   A receiver MUST accept packets containing an
#   outdated quic_frame, such as a MAX_quic_framequic_frame carrying a smaller maximum
#   data than one found in an older packet.
# => test where we send packet only with max_data with random value we should be ack for all packet 
#    if good

before quic_frame.max_data.handquic_framequic_frame.max_data,scid:cid,dcid:cid,e:quic_packet_type,seq_num:pkt_num) {
    if _generating {
        require f.pos > 0;
    }
}

export quic_frame.max_streams.handle
export quic_frame.max_stream_data.handle
export quic_frame.max_data.handle
#export quic_frame.stream_blocked.handle
export quic_frame.rst_stream.handle

attribute quic_frame.rst_stream.handle.weight = "0.02"
attribute quic_frame.max_data.handle.weight = "5"


# export quic_frame.connection_close.handle
# attribute quic_frame.connection_close.handle.weight = "0.02"

#export quic_frame.application_close.handle
#attribute quic_frame.application_close.handle.weight = "0.02"

export quic_frame.stop_sending.handle
