#lang ivy1.7

#    Message transmission is controlled by the following parameters:

#                    +-------------------+---------------+
#                    | name              | default value |
#                    +-------------------+---------------+
#                    | ACK_TIMEOUT       | 2 seconds     |
#                    | ACK_RANDOM_FACTOR | 1.5           |
#                    | MAX_RETRANSMIT    | 4             |
#                    | NSTART            | 1             |
#                    | DEFAULT_LEISURE   | 5 seconds     |
#                    | PROBING_RATE      | 1 byte/second |
#                    +-------------------+---------------+

#                      Table 2: CoAP Protocol Parameters