#lang ivy1.7

action make_transport_parameters returns (tp:quic_transport_parameters) = {
    var imsdbl : initial_max_stream_data_bidi_local;
    imsdbl.stream_pos_32 := max_stream_data;
    var imd : initial_max_data;
    imd.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    var it : max_idle_timeout;
    it.seconds_16 := 0x9C40; #0x3A98; #random_microsecs(0,0xFFFFFFF); 15sec
    var imsdbr : initial_max_stream_data_bidi_remote;
    imsdbr.stream_pos_32 := max_stream_data;
    var imsdu : initial_max_stream_data_uni;
    imsdu.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    tp.transport_parameters := tp.transport_parameters.append(imsdbl);
    tp.transport_parameters := tp.transport_parameters.append(imd);
    tp.transport_parameters := tp.transport_parameters.append(it);
    tp.transport_parameters := tp.transport_parameters.append(imsdbr);
    tp.transport_parameters := tp.transport_parameters.append(imsdu);

    var icid : initial_source_connection_id; #TODO update v29
    icid.scid := the_cid;
    tp.transport_parameters := tp.transport_parameters.append(icid);

    var max_streams_uni : initial_max_stream_id_uni; #TODO update rfc9000
    max_streams_uni.stream_id_16 := random_stream_id(4,0xFFFFFFF);
    tp.transport_parameters := tp.transport_parameters.append(max_streams_uni);

    var max_ack_dela : max_ack_delay; #TODO update rfc9000 -> ERROR
    max_ack_dela.exponent_8 := 0x4000; #random_microsecs(0x20,0x4000);
    local_max_ack_delay_tp := milliseconds_to_microseconds(max_ack_dela.exponent_8);
    tp.transport_parameters := tp.transport_parameters.append(max_ack_dela);

    var max_streams_bidi : initial_max_stream_id_bidi; #TODO update v29
    max_streams_bidi.stream_id_16 := random_stream_id(4,0xFFFFFFF);
    tp.transport_parameters := tp.transport_parameters.append(max_streams_bidi);


    var no_migration : disable_active_migration; #TODO update v29
    tp.transport_parameters := tp.transport_parameters.append(no_migration);


    # var max_packet_z : max_packet_size; #TODO update rfc9000
    # max_packet_z.stream_pos_16 := 1500;
    # tp.transport_parameters := tp.transport_parameters.append(max_packet_z);
}