# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'standard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.constants import *
from gui.terminal_widget import embeddedTerminal
from run_experiments import *

class UIvyQUICExperiments(object):

    def __init__(self, dir_path=None,experiments=None):
        self.dir_path = dir_path
        self.ivy_temps_path = dir_path + "/QUIC-Ivy-Attacker/doc/examples/quic/test/temp/"
        self.server_tests = []
        self.server_tests_checkbox = []
        for cate in TESTS_SERVER:
            for test in TESTS_SERVER[cate]:
                self.server_tests.append(test)
        self.client_tests = []
        self.client_tests_checkbox = []
        for cate in TESTS_CLIENT:
            for test in TESTS_CLIENT[cate]:
                self.client_tests.append(test)

        self.implem_tests_checkbox = []

        self.experiments = experiments


    def setupUi(self, IvyQUIC):
        IvyQUIC.setObjectName("IvyQUIC")
        IvyQUIC.resize(933, 703)
        
        self.centralwidget = QtWidgets.QWidget(IvyQUIC)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 298, 639))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10, 0, QtCore.Qt.AlignTop)

        for server_test in self.server_tests:
            checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
            checkBox.setObjectName("checkBox_3")
            self.server_tests_checkbox.append({"name": server_test, "checkbox": checkBox})
            self.verticalLayout_2.addWidget(checkBox)

        # self.checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        # self.checkBox.setObjectName("checkBox")
        # self.verticalLayout_2.addWidget(self.checkBox)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)

        for client_test in self.client_tests:
            checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
            checkBox.setObjectName("checkBox_3")
            self.server_tests_checkbox.append({"name": client_test, "checkbox": checkBox})
            self.verticalLayout_2.addWidget(checkBox)

        # self.checkBox_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        # self.checkBox_6.setObjectName("checkBox_6")
        # self.verticalLayout_2.addWidget(self.checkBox_6)
        # self.checkBox_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        # self.checkBox_5.setObjectName("checkBox_5")
        # self.verticalLayout_2.addWidget(self.checkBox_5)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setMaximumSize(QtCore.QSize(220, 107))
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout.addWidget(self.scrollArea)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 297, 639))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2, 0, QtCore.Qt.AlignTop)
        # self.checkBox_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents_2)
        # self.checkBox_2.setObjectName("checkBox_2")
        # self.verticalLayout_3.addWidget(self.checkBox_2)
        for implem in IMPLEMENTATIONS.keys():
            checkBox = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
            checkBox.setObjectName("checkBox_3")
            self.implem_tests_checkbox.append({"name": implem, "checkbox": checkBox})
            self.verticalLayout_3.addWidget(checkBox)

        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout.addWidget(self.scrollArea_2)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 302, 639))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents_4)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.setup_pushButton)
        self.verticalLayout_5.addWidget(self.pushButton)
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignTop)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setProperty("value", 1)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_6.addWidget(self.spinBox)

        self.verticalLayout_exemode = QtWidgets.QVBoxLayout()
        self.verticalLayout_exemode.setObjectName("verticalLayout_exemode")
        self.groupBox_exemode = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_exemode.setObjectName("groupBox_exemode")
        self.groupBox_exemode.setLayout(self.verticalLayout_exemode)

        # self.label_4 = QtWidgets.QLabel(self.groupBox_exemode)
        # self.label_4.setObjectName("label_4")
        self.verticalLayout_6.addWidget(self.groupBox_exemode)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_exemode)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_exemode.addWidget(self.radioButton_2)
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_exemode)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_exemode.addWidget(self.radioButton)

        self.verticalLayout_network = QtWidgets.QVBoxLayout()
        self.verticalLayout_network.setObjectName("verticalLayout_network")
        self.groupBox_network = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_network.setObjectName("groupBox_network")
        self.groupBox_network.setLayout(self.verticalLayout_network)

        # self.label_5 = QtWidgets.QLabel(self.groupBox_network)
        # self.label_5.setObjectName("label_5")
        self.verticalLayout_6.addWidget(self.groupBox_network)
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_network)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_network.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox_network)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_network.addWidget(self.radioButton_4)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.listWidget = QtWidgets.QListWidget(self.groupBox)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_6.addWidget(self.listWidget)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout_6.addWidget(self.listWidget_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.spinBox_2 = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_2.setProperty("value", 30)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_6.addWidget(self.spinBox_2)
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout_6.addWidget(self.checkBox_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_7.addLayout(self.verticalLayout_5)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayout.addWidget(self.scrollArea_3)
        IvyQUIC.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(IvyQUIC)
        self.statusbar.setObjectName("statusbar")
        IvyQUIC.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(IvyQUIC)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 933, 22))
        self.menubar.setObjectName("menubar")
        self.menuTest_mode = QtWidgets.QMenu(self.menubar)
        self.menuTest_mode.setObjectName("menuTest_mode")
        IvyQUIC.setMenuBar(self.menubar)
        self.actionStandard = QtWidgets.QAction(IvyQUIC)
        self.actionStandard.setObjectName("actionStandard")
        self.actionAttacker = QtWidgets.QAction(IvyQUIC)
        self.actionAttacker.setObjectName("actionAttacker")
        self.menuTest_mode.addAction(self.actionStandard)
        self.menuTest_mode.addAction(self.actionAttacker)
        self.menubar.addAction(self.menuTest_mode.menuAction())

        self.retranslateUi(IvyQUIC)
        QtCore.QMetaObject.connectSlotsByName(IvyQUIC)

    def setup_pushButton(self):
        import os
        current_exp = self.ivy_temps_path + str(self.spinBox.value())
        dirs = os.listdir( current_exp )
        for server_test in self.server_tests_checkbox:
            if server_test["checkbox"].isChecked():
                pass
                
        
    def retranslateUi(self, IvyQUIC):
        _translate = QtCore.QCoreApplication.translate
        IvyQUIC.setWindowTitle(_translate("IvyQUIC", "Ivy QUIC - Classical"))
        self.label.setText(_translate("IvyQUIC", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AVAILABLE TESTS</span></p></body></html>"))
        self.label_10.setText(_translate("IvyQUIC", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Server tests</span></p></body></html>"))
        for checkbox in self.server_tests_checkbox:
            checkbox["checkbox"].setText(_translate("IvyQUIC", checkbox["name"]))
        # self.checkBox_3.setText(_translate("IvyQUIC", "Test 1"))
        # self.checkBox.setText(_translate("IvyQUIC", "Test 2"))
        self.label_11.setText(_translate("IvyQUIC", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Client tests</span></p></body></html>"))
        for checkbox in self.client_tests_checkbox:
            checkbox["checkbox"].setText(_translate("IvyQUIC", checkbox["name"]))
        # self.checkBox_6.setText(_translate("IvyQUIC", "Test 1"))
        # self.checkBox_5.setText(_translate("IvyQUIC", "Test 2"))
        self.label_2.setText(_translate("IvyQUIC", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">AVAILABLE IMPLEMENTATIONS</span></p></body></html>"))
        
        # self.checkBox_2.setText(_translate("IvyQUIC", "Implementation 1"))
        for checkbox in self.implem_tests_checkbox:
            checkbox["checkbox"].setText(_translate("IvyQUIC", checkbox["name"]))
        self.pushButton.setText(_translate("IvyQUIC", "Start\nexperiments"))
        self.groupBox.setTitle(_translate("IvyQUIC", "Parameters"))
        self.label_3.setText(_translate("IvyQUIC", "<html><head/><body><p><span style=\" font-weight:600;\">Number of iterations</span></p></body></html>"))
        self.groupBox_exemode.setTitle(_translate("IvyQUIC", "Execution mode"))
        self.radioButton_2.setText(_translate("IvyQUIC", "Run on docker"))
        self.radioButton.setText(_translate("IvyQUIC", "Run locally"))
        self.groupBox_network.setTitle(_translate("IvyQUIC", "Network mode"))
        self.radioButton_3.setText(_translate("IvyQUIC", "localhost"))
        self.radioButton_4.setText(_translate("IvyQUIC", "vnet"))
        self.label_6.setText(_translate("IvyQUIC", "<html><head/><body><p><span style=\" font-weight:600;\">Others</span></p></body></html>"))
        self.label_7.setText(_translate("IvyQUIC", "<html><head/><body><p><span style=\" font-style:italic;\">Initial version</span></p></body></html>"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("IvyQUIC", "draft 29"))
        item = self.listWidget.item(1)
        item.setText(_translate("IvyQUIC", "draft 28"))
        item = self.listWidget.item(2)
        item.setText(_translate("IvyQUIC", "RFC9000"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("IvyQUIC", "<html><head/><body><p><span style=\" font-style:italic;\">Initial alpn</span></p></body></html>"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("IvyQUIC", "hq-29"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("IvyQUIC", "hq-28"))
        item = self.listWidget_2.item(2)
        item.setText(_translate("IvyQUIC", "hq-interop"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.label_9.setText(_translate("IvyQUIC", "<html><head/><body><p><span style=\" font-style:italic;\">Timeout (sec)</span></p></body></html>"))
        self.checkBox_4.setText(_translate("IvyQUIC", "Allow migration"))
        self.menuTest_mode.setTitle(_translate("IvyQUIC", "Test mode"))
        self.actionStandard.setText(_translate("IvyQUIC", "Standard"))
        self.actionAttacker.setText(_translate("IvyQUIC", "Attacker"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IvyQUIC = QtWidgets.QMainWindow()
    ui = UIvyQUICExperiments()
    ui.setupUi(IvyQUIC)
    IvyQUIC.show()
    sys.exit(app.exec_())
