language: c
sudo: false
addons:
  apt:
matrix:
    include:
        - name: Linux (gcc-8)
          os: linux
          dist: xenial
          compiler: gcc-8
          addons:
             apt:
               sources:
                 - ubuntu-toolchain-r-test
               packages: g++-8
        - name: Linux (clang)
          os: linux
          dist: xenial
          compiler: clang
before_install:
  - $CC --version
  - cmake --version
before_script:
  - cmake .
script:
  - make
  - make test
