ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD miniP.h ping-pong-mt/miniP.h
ADD delay.h ping-pong-mt/delay.h
ADD miniP_client.c ping-pong-mt/miniP_client.c
ADD miniP_server_mt_fonctionnel.c ping-pong-mt/miniP_server_mt_fonctionnel.c

RUN cd ping-pong-mt/; gcc miniP_client.c -o miniP_client && gcc miniP_server_mt_fonctionnel.c -o miniP_server -lpthread

WORKDIR /app