#!/usr/bin/env python3
"""
PANTHER Build Mapping Generator

Integration module for panther_builder.py to replace manual build_dict
with automated discovery-based generation.

This module provides the interface for panther_builder.py to call
automated build_dict generation, replacing the 85+ manual mappings
with intelligent discovery.

Usage in panther_builder.py:
    from panther.tools.docs_gen.generate_build_mapping import get_build_dict

    # Replace manual build_dict with:
    build_dict = get_build_dict()
"""

import sys
from pathlib import Path
from typing import Dict


def get_build_dict(project_root: Path = None, use_cache: bool = True) -> Dict[str, str]:
    """
    Get automated build_dict for documentation generation.

    Args:
        project_root: Project root directory (auto-detected if None)
        use_cache: Use cached results if available (faster)

    Returns:
        Dictionary mapping source README files to documentation targets

    Example:
        build_dict = get_build_dict()
        # Returns: {"README.md": "docs/index.md", ...}
    """

    # Auto-detect project root if not provided
    if project_root is None:
        current_dir = Path(__file__).parent
        # Look for panther_builder.py to identify project root
        for parent in [current_dir] + list(current_dir.parents):
            if (parent / "panther_builder.py").exists():
                project_root = parent
                break

        if project_root is None:
            raise RuntimeError(
                "Could not find project root (looking for panther_builder.py)"
            )

    # Check for cached build_dict
    cache_file = (
        project_root / "panther" / "tools" / "docs-gen" / "generated_build_dict.py"
    )

    if use_cache and cache_file.exists():
        try:
            # Import the cached build_dict
            import importlib.util

            spec = importlib.util.spec_from_file_location(
                "cached_build_dict", cache_file
            )
            cached_module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(cached_module)

            return cached_module.build_dict

        except Exception as e:
            print(f"Warning: Could not load cached build_dict: {e}")
            print("Generating fresh build_dict...")

    # Generate fresh build_dict using discovery system
    return _generate_fresh_build_dict(project_root)


def _generate_fresh_build_dict(project_root: Path) -> Dict[str, str]:
    """Generate build_dict using the discovery system."""

    try:
        # Import discovery system
        from .discover_sources import PantherSourceDiscovery

        # Create discovery instance and generate mappings
        discovery = PantherSourceDiscovery(project_root)
        build_dict = discovery.generate_build_dict()

        # Cache the results for future use
        _cache_build_dict(project_root, build_dict)

        return build_dict

    except ImportError as e:
        print(f"Error: Could not import discovery system: {e}")
        print("Falling back to emergency manual mappings...")
        return _get_emergency_mappings()


def _cache_build_dict(project_root: Path, build_dict: Dict[str, str]) -> None:
    """Cache the generated build_dict for faster future access."""

    try:
        cache_file = (
            project_root / "panther" / "tools" / "docs-gen" / "generated_build_dict.py"
        )

        # Ensure directory exists
        cache_file.parent.mkdir(parents=True, exist_ok=True)

        # Write cached build_dict
        with open(cache_file, "w") as f:
            f.write("# Generated build_dict\n")
            f.write("# Auto-generated by generate_build_mapping.py\n")
            f.write("# Do not edit manually - regenerate using discover_sources.py\n\n")
            f.write("build_dict = {\n")
            for source, target in build_dict.items():
                f.write(f'    "{source}": "{target}",\n')
            f.write("}\n")

        print(f"✓ Build dict cached to {cache_file}")

    except Exception as e:
        print(f"Warning: Could not cache build_dict: {e}")


def _get_emergency_mappings() -> Dict[str, str]:
    """Emergency fallback mappings if discovery system fails."""

    print("⚠️  Using emergency fallback mappings")

    # Core essential mappings only
    return {
        "README.md": "docs/index.md",
        "QUICK_START.md": "docs/QUICK_START.md",
        "INSTALL.md": "docs/INSTALL.md",
        "CONTRIBUTING.md": "docs/contributing.md",
        "panther/config/README.md": "docs/configuration.md",
        "panther/core/README.md": "docs/core.md",
        "panther/plugins/README.md": "docs/plugins_overview.md",
        "CHANGELOG.md": "docs/changelog.md",
        "LICENSE.md": "docs/license.md",
    }


def regenerate_build_dict(project_root: Path = None) -> Dict[str, str]:
    """
    Force regeneration of build_dict (ignoring cache).

    Useful for development or when README files have been added/removed.

    Args:
        project_root: Project root directory (auto-detected if None)

    Returns:
        Freshly generated build_dict
    """

    return get_build_dict(project_root=project_root, use_cache=False)


def validate_build_dict(build_dict: Dict[str, str], project_root: Path = None) -> bool:
    """
    Validate that all source files in build_dict exist.

    Args:
        build_dict: The build dictionary to validate
        project_root: Project root directory (auto-detected if None)

    Returns:
        True if all source files exist, False otherwise
    """

    if project_root is None:
        current_dir = Path(__file__).parent
        for parent in [current_dir] + list(current_dir.parents):
            if (parent / "panther_builder.py").exists():
                project_root = parent
                break

    if project_root is None:
        print("Error: Could not find project root for validation")
        return False

    missing_files = []
    for source_file in build_dict.keys():
        source_path = project_root / source_file
        if not source_path.exists():
            missing_files.append(source_file)

    if missing_files:
        print(f"⚠️  Missing source files:")
        for missing in missing_files:
            print(f"    - {missing}")
        return False

    print(f"✓ All {len(build_dict)} source files validated")
    return True


# Convenience function for direct usage
def get_automated_build_dict() -> Dict[str, str]:
    """
    Convenience function that returns automated build_dict.

    This is the main function that panther_builder.py should call
    to replace the manual build_dict.

    Returns:
        Automated build_dict mapping README files to docs/ targets
    """
    return get_build_dict()


if __name__ == "__main__":
    """Command-line interface for testing and utilities."""

    if len(sys.argv) > 1:
        command = sys.argv[1]

        if command == "--regenerate":
            print("🔄 Regenerating build_dict...")
            build_dict = regenerate_build_dict()
            print(f"✓ Generated {len(build_dict)} mappings")

        elif command == "--validate":
            print("✅ Validating build_dict...")
            build_dict = get_build_dict()
            is_valid = validate_build_dict(build_dict)
            sys.exit(0 if is_valid else 1)

        elif command == "--show":
            print("📋 Current build_dict:")
            build_dict = get_build_dict()
            for source, target in sorted(build_dict.items()):
                print(f"  {source} -> {target}")

        else:
            print(f"Unknown command: {command}")
            print("Available commands: --regenerate, --validate, --show")
            sys.exit(1)
    else:
        # Default: show build_dict
        build_dict = get_build_dict()
        print(f"Generated build_dict with {len(build_dict)} mappings")
        print("Use --show to display all mappings")
