"""Auto-generated build dictionary mapping for documentation sources."""

# Generated build_dict
# Auto-generated by generate_build_mapping.py
# Do not edit manually - regenerate using discover_sources.py

build_dict = {
    "README.md": "docs/index.md",
    "INSTALL.md": "docs/INSTALL.md",
    "QUICK_START.md": "docs/QUICK_START.md",
    "workflow.md": "docs/workflow.md",
    "panther/plugins/plugins_inventory.md": "docs/plugins_inventory.md",
    "panther/plugins/__init__.py": "docs/plugin_development.md",
    "CONTRIBUTING.md": "docs/contributing.md",
    "CHANGELOG.md": "docs/changelog.md",
    "LICENSE.md": "docs/license.md",
}
