@startuml
title /home/user/Documents/QUIC-RFC9000/QUIC-Ivy/doc/examples/quic/test/temp/45/quic_client_test_version_negociation_mim_modify0.iev
skinparam sequenceMessageAlign center
"IvyAgent0" --> "TestedAgent1" : **Initial Packet** \n\n
note left
frame.ping:[]...]
frame.crypto:[offset:0,length:0x121,data:...]
end note

"TestedAgent1" --> "IvyAgent0" : **Initial Packet** \n\n
note right
frame.crypto:[offset:0,length:0x7b,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **Handshake Packet** \n\n
note left
frame.ping:[]]]])
]...]
end note

"TestedAgent1" --> "IvyAgent0" : **Handshake Packet** \n\n
note right
frame.crypto:[offset:0,length:0x540,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **Handshake Packet** \n\n
note left
frame.ack:[largest_acked:0x1,ack_delay:0x13,ack_ranges:[[gap:0,ranges:0]]]...]
frame.crypto:[offset:0,length:0x24,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.new_connection_id:[seq_num:0x1,retire_prior_to:0,length:0x8,scid:15046606706880839274,token:0x94fdf5b6]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0,offset:0,length:0x11,data:...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0,offset:0,length:0x4,data:...]
frame.handshake_done:[]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0x4,offset:0,length:0x10,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x1,ack_delay:0x913,ack_ranges:[[gap:0,ranges:0]]]]]])
]...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0x4,offset:0,length:0x4,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0,offset:0,length:0x11,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0x8,offset:0,length:0xe,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x2,ack_delay:0x4fa,ack_ranges:[[gap:0,ranges:0x1]]]]]])
]...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0x5,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0x8,offset:0,length:0x4,data:...]
frame.ack:[largest_acked:0x6,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0x4,offset:0,length:0x10,data:...]
frame.stream:[off:0,len:0x1,fin:0x1,id:0,offset:0,length:0x11,data:...]
frame.stream:[off:0,len:0x1,fin:0x1,id:0xc,offset:0,length:0xf,data:...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0x5,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0x8,offset:0,length:0x4,data:...]
frame.ack:[largest_acked:0x6,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x3,ack_delay:0x4d23,ack_ranges:[[gap:0,ranges:0x1]]]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x4,ack_delay:0xc07,ack_ranges:[[gap:0,ranges:0x2]]]]]])
]...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0x7,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0xc,offset:0,length:0x4,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.stream:[off:0,len:0x1,fin:0x1,id:0x10,offset:0,length:0x18,data:...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0x7,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0xc,offset:0,length:0x4,data:...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x5,ack_delay:0x268e,ack_ranges:[[gap:0,ranges:0x3]]]]]])
]...]
end note

"TestedAgent1" --> "IvyAgent0" : **One RTT Packet** \n\n
note right
frame.ack:[largest_acked:0x7,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]...]
frame.stream:[off:0x1,len:0x1,fin:0x1,id:0xc,offset:0,length:0x4,data:...]
frame.ack:[largest_acked:0x8,ack_delay:0,ack_ranges:[[gap:0,ranges:0]]]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x6,ack_delay:0x4ed,ack_ranges:[[gap:0,ranges:0x4]]]]]])
]...]
end note

"IvyAgent0" --> "TestedAgent1" : **One RTT Packet** \n\n
note left
frame.ack:[largest_acked:0x7,ack_delay:0x4ec,ack_ranges:[[gap:0,ranges:0x3]]]]]])
]...]
end note

@enduml
