#lang ivy1.7

# Is it the most elegant way to reprensent error ?
# https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-20

# tag = 0x0
relation is_no_error  

# tag = 0x1
relation is_internal_error 

# tag = 0x2
relation is_server_busy 

# tag = 0x3
relation is_flow_control_error

# tag = 0x4
relation is_stream_limit_error 

# tag = 0x5
relation is_stream_state_error 

# tag = 0x6
relation is_final_size_error  

# tag = 0x7
relation is_frame_encoding_error 

# tag = 0x8
relation is_transport_parameter_error 

# tag = 0x9
relation is_connection_id_limit_error  

# tag = 0xa
relation is_protocol_violation  

# tag = 0xb
relation is_invalid_token 

# tag = 0xc
relation is_application_error 

# tag = 0xd
relation is_crypto_buffer_exceeded 

# tag = 0xe
relation is_key_update_error 

# tag = 0xf
relation is_aead_limit_reached

# tag = 0x10
relation is_no_viable_path

# tag = 0x1XX - 0x01ff
relation is_crypto_error  

# tag = 0x53F8 https://datatracker.ietf.org/doc/html/draft-ietf-quic-version-negotiation#page-11
relation is_version_negociation_error

# Initial state
# -------------

after init {
    is_no_error := true; # TODO
    is_internal_error := false;
    is_server_busy := false;
    is_flow_control_error := false;
    is_stream_limit_error := false;
    is_stream_state_error := false;
    is_final_size_error := false;
    is_frame_encoding_error := false;
    is_transport_parameter_error := false;
    is_connection_id_limit_error := false;
    is_protocol_violation := false;
    is_invalid_token := false;
    is_application_error := false;
    is_crypto_buffer_exceeded := false;
    is_crypto_error := false;
    is_version_negociation_error := false;
}

action handle_transport_error(ec:error_code) =
{
    if ec = 0x0 {
        is_no_error := true;
    } else if ec = 0x1 {
        is_internal_error := true;
        is_no_error := false;
    } else if ec = 0x2 {
        is_server_busy := true;
        is_no_error := false;
    } else if ec = 0x3 {
        is_flow_control_error := true;
        is_no_error := false;
    } else if ec = 0x4 {
        is_stream_limit_error := true;
        is_no_error := false;
    } else if ec = 0x5 {
        is_stream_state_error := true;
        is_no_error := false;
    } else if ec = 0x6 {
        is_final_size_error := true;
        is_no_error := false;
    } else if ec = 0x7 {
        is_frame_encoding_error := true;
        is_no_error := false;
    } else if ec = 0x8 {
        is_transport_parameter_error := true;
        is_no_error := false;
    } else if ec = 0x9 {
        is_connection_id_limit_error := true;
        is_no_error := false;
    } else if ec = 0xa {
        is_protocol_violation := true;
        is_no_error := false;
    } else if ec = 0xb {
        is_invalid_token := true;
        is_no_error := false;
    } else if ec = 0xc {
        is_application_error := true;
        is_no_error := false;
    } else if ec = 0xd {
        is_crypto_buffer_exceeded := true;
    } else if ec = 0xe {
        is_key_update_error := true;
    } else if ec = 0xf {
        is_aead_limit_reached := true;
    } else if ec = 0x10 {
        is_no_viable_path := true;
    } else if ec = 0x53F8 {
        is_version_negociation_error := true;
        is_no_error := false;
    }else {
        # TODO check if tag = 0x1XX
        is_crypto_error := true;
        is_no_error := false;
    }
}
