ARG image

FROM $image:latest

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    && curl \
    -L \
    -o openjdk.tar.gz \
    https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz \
    && mkdir jdk \
    && tar zxf openjdk.tar.gz -C jdk --strip-components=1 \
    && rm -rf openjdk.tar.gz \
    && apt-get -y --purge autoremove curl \
    && ln -sf /opt/jdk/bin/* /usr/local/bin/ \
    && rm -rf /var/lib/apt/lists/* \
    && java  --version \
    && javac --version \
    && jlink --version

WORKDIR /app/implementations/system-implementations/mark/

RUN git clone https://gitlab.cylab.be/cylab/mark.git .

WORKDIR /app/implementations/system-implementations/mark-server/

COPY /app/implementations/system-implementations/mark/server/src/scripts/run.sh /app/implementations/system-implementations/mark/server/src/scripts/config.yml /app/implementations/system-implementations/mark-server/

COPY /app/implementations/system-implementations/mark/server/target/*.jar /app/implementations/system-implementations/mark-server/bin/
RUN rm /app/implementations/system-implementations/mark-server/bin/*-javadoc.jar/app/implementations/system-implementations/mark-server/bin/*-sources.jar

COPY /app/implementations/system-implementations/mark/server/target/libs/*.jar /app/implementations/system-implementations/mark-server/libs/
RUN mkdir -p /app/implementations/system-implementations/mark-server/logs/ /app/implementations/system-implementations/mark-server/modules/
