FROM shadow_ns_v1_panther:latest

FROM picoquic_shadow_rfc9000_panther:latest

EXPOSE 4443:4443
EXPOSE 8080:8080
# Set container working directory
# WORKDIR "/opt/picoquic"

# Add service-specific environment variables
ENV ROLE="server"
ENV UID=${UID}
ENV GID=${GID}

# Copy logs and volumes
VOLUME /app/logs
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/cert.pem:/opt/certs/cert.pem"
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/key.pem:/opt/certs/key.pem"
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/ticket.key"

# Define the command for the service

FROM picoquic_shadow_rfc9000_panther:latest

EXPOSE 5000:5000
EXPOSE 8081:8081
# Set container working directory
# WORKDIR "/opt/picoquic"

# Add service-specific environment variables
ENV ROLE="client"
ENV UID=${UID}
ENV GID=${GID}

# Copy logs and volumes
VOLUME /app/logs
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/cert.pem:/opt/certs/cert.pem"
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/key.pem:/opt/certs/key.pem"
VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/ticket.key"

# Define the command for the service


WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root
COPY --from=shadow_ns_v1_panther /shadow /shadow
COPY --from=shadow_ns_v1_panther /root/.cargo/ /root/.cargo/
COPY --from=shadow_ns_v1_panther /root/.local/ /root/.local/
COPY --from=shadow_ns_v1_panther /usr/include/shadow.h /usr/include/shadow.h
COPY --from=shadow_ns_v1_panther /etc/shadow /etc/shadow

ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"
ENV PATH="/shadow/build:/root/shadow/build/:${PATH}"
# ENV PATH="/cmake-3.26.4-linux-x86_64/bin:/root/.cargo/bin:/root/.local/bin/:/root/shadow/:${PATH}"
# ENV LD_LIBRARY_PATH="/root/.local/lib:/root/shadow/build/src/lib/preload-injector:${LD_LIBRARY_PATH}"
RUN rustup default stable

ADD shadow.generated.yml /shadow_ns_config.yml
ENV RUST_BACKTRACE=1
ENTRYPOINT [ "/bin/sh", "-l", "-c" ]
# ENTRYPOINT [ "shadow", "/shadow_ns_config.yml" ]
