FROM shadow_ns_v1_panther:latest AS shadow_base

FROM ping_pong_functional_panther:latest AS ping_pong_client_stage

# Copy files from the service stage to /opt in the final image
EXPOSE 5000:5000
EXPOSE 8081:8081

# Set container working directory
# WORKDIR "/opt/ping-pong/"

# Add service-specific environment variables
ENV ROLE="client"
ENV UID=${UID}
ENV GID=${GID}
ENV SHADOW_TEST="1"

# Define the command for the service
RUN <<EOF
echo "Running pre-compilation commands:"
set -x;
export PATH=$$PATH:$$ADDITIONAL_PATH;
export PYTHONPATH=$$PYTHONPATH:$$ADDITIONAL_PYTHONPATH;
env >> /app/logs/ivy_setup.log;
TARGET_IP=$(getent hosts ping_pong_server | awk "{ print \$1 }");
echo "Resolved ping_pong_server IP - $$TARGET_IP" >> /app/logs/ivy_setup.log;
IVY_IP=$(hostname -I | awk "{ print \$1 }");
echo "Resolved  ping_pong_client IP - $$IVY_IP" >> /app/logs/ivy_setup.log;
 
ip_to_hex() {
  echo $1 | awk -F"." "{ printf(\"%02X%02X%02X%02X\", \$1, \$2, \$3, \$4) }";
}
 
ip_to_decimal() {
  echo $1 | awk -F"." "{ printf(\"%.0f\", (\$1 * 256 * 256 * 256) + (\$2 * 256 * 256) + (\$3 * 256) + \$4) }";
}
 
TARGET_IP_HEX=$(ip_to_decimal $$TARGET_IP);
IVY_IP_HEX=$(ip_to_decimal $$IVY_IP);
echo "Resolved ping_pong_server IP in hex - $$TARGET_IP_HEX" >> /app/logs/ivy_setup.log;
echo "Resolved ping_pong_client IP in hex - $$IVY_IP_HEX" >> /app/logs/ivy_setup.log;
EOF

RUN <<EOF
echo "Running compilation commands:"
EOF

RUN <<EOF
echo "Running post-compilation commands:"
EOF
FROM ping_pong_functional_panther:latest AS ping_pong_server_stage

# Copy files from the service stage to /opt in the final image
EXPOSE 4443:4443
EXPOSE 4987:4987
EXPOSE 8080:8080

# Set container working directory
# WORKDIR "/opt/ping-pong/"

# Add service-specific environment variables
ENV ROLE="server"
ENV UID=${UID}
ENV GID=${GID}
ENV SHADOW_TEST="1"

# Define the command for the service
RUN <<EOF
echo "Running pre-compilation commands:"
set -x;
export PATH=$$PATH:$$ADDITIONAL_PATH;
export PYTHONPATH=$$PYTHONPATH:$$ADDITIONAL_PYTHONPATH;
env >> /app/logs/ivy_setup.log;
TARGET_IP=$(getent hosts  | awk "{ print \$1 }");
echo "Resolved  IP - $$TARGET_IP" >> /app/logs/ivy_setup.log;
IVY_IP=$(hostname -I | awk "{ print \$1 }");
echo "Resolved  ping_pong_server IP - $$IVY_IP" >> /app/logs/ivy_setup.log;
 
ip_to_hex() {
  echo $1 | awk -F"." "{ printf(\"%02X%02X%02X%02X\", \$1, \$2, \$3, \$4) }";
}
 
ip_to_decimal() {
  echo $1 | awk -F"." "{ printf(\"%.0f\", (\$1 * 256 * 256 * 256) + (\$2 * 256 * 256) + (\$3 * 256) + \$4) }";
}
 
TARGET_IP_HEX=$(ip_to_decimal $$TARGET_IP);
IVY_IP_HEX=$(ip_to_decimal $$IVY_IP);
echo "Resolved  IP in hex - $$TARGET_IP_HEX" >> /app/logs/ivy_setup.log;
echo "Resolved ping_pong_server IP in hex - $$IVY_IP_HEX" >> /app/logs/ivy_setup.log;
EOF

RUN <<EOF
echo "Running compilation commands:"
EOF

RUN <<EOF
echo "Running post-compilation commands:"
EOF

# Final stage
FROM shadow_ns_v1_panther:latest
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root

COPY --from=ping_pong_client_stage /opt /opt/ping_pong_client
COPY --from=ping_pong_server_stage /opt /opt/ping_pong_server

COPY --from=shadow_ns_v1_panther /shadow /shadow
COPY --from=shadow_ns_v1_panther /root/.cargo/ /root/.cargo/
COPY --from=shadow_ns_v1_panther /root/.local/ /root/.local/
COPY --from=shadow_ns_v1_panther /usr/include/shadow.h /usr/include/shadow.h
COPY --from=shadow_ns_v1_panther /etc/shadow /etc/shadow

ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"
ENV PATH="/shadow/build:/root/shadow/build/:${PATH}"
RUN rustup default stable
RUN rm -rf shadow.data/

ADD shadow_ns.generated.yml /shadow_ns_config.yml
ENV RUST_BACKTRACE=1
ENTRYPOINT [ "/bin/sh", "-c", "shadow /shadow_ns_config.yml --data-directory /app/logs/shadow.data > /app/logs/shadow_stdout.log 2> /app/logs/shadow_stderr.log; cp /opt/ping_pong_client/ping-pong/miniP_* /app/logs/ping_pong_client/miniP_*;cp /opt/ping_pong_server/ping-pong/miniP_* /app/logs/ping_pong_server/miniP_*;" ]
