FROM shadow_ns_v1_panther:latest

{% for service_name, service in services.items() %}
{% if service.type == "tester" %}
FROM {{ service.implementation }}_{{ service.protocol.version }}_panther:latest
{% else %}
FROM {{ service.implementation }}_{{ service.version }}_panther:latest
{% endif %}

{% for port in service.ports %}
EXPOSE {{ port }}
{% endfor %}# Set container working directory
# WORKDIR "{{ deployment_info[service_name]['working_dir'] }}"

# Add service-specific environment variables
ENV ROLE="{{ service.role }}"
ENV UID=${UID}
ENV GID=${GID}
{% if "environment" in deployment_info[service_name] %}
{% for key, value in deployment_info[service_name]["environment"].items() %}
ENV {{ key }}="{{ value }}"
{% endfor %}
{% endif %}

# Copy logs and volumes
VOLUME /app/logs
{% for volume in deployment_info[service_name]['volumes'] %}
{% if volume | is_dict %}
VOLUME "{{ volume.local | realpath }}:{{ volume.container }}"
{% else %}
VOLUME "{{ volume }}"
{% endif %}
{% endfor %}

# Define the command for the service
{% if "ivy" in service_name %}
CMD ["/bin/sh", "-c", {{ deployment_info[service_name]['compilation_command'] }}]
{% endif %}

{% endfor %}

WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root
COPY --from=shadow_ns_v1_panther /shadow /shadow
COPY --from=shadow_ns_v1_panther /root/.cargo/ /root/.cargo/
COPY --from=shadow_ns_v1_panther /root/.local/ /root/.local/
COPY --from=shadow_ns_v1_panther /usr/include/shadow.h /usr/include/shadow.h
COPY --from=shadow_ns_v1_panther /etc/shadow /etc/shadow

ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"
ENV PATH="/shadow/build:/root/shadow/build/:${PATH}"
# ENV PATH="/cmake-3.26.4-linux-x86_64/bin:/root/.cargo/bin:/root/.local/bin/:/root/shadow/:${PATH}"
# ENV LD_LIBRARY_PATH="/root/.local/lib:/root/shadow/build/src/lib/preload-injector:${LD_LIBRARY_PATH}"
RUN rustup default stable

ADD {{ shadow_ns_config_file }} /shadow_ns_config.yml
ENV RUST_BACKTRACE=1
ENTRYPOINT [ "/bin/sh", "-l", "-c" ]
# ENTRYPOINT [ "shadow", "/shadow_ns_config.yml" ]

