FROM shadow_ns_v1_panther:latest AS shadow_base


FROM picoquic_shadow_rfc9000_panther:latest AS picoquic_server_stage

# Copy files from the service stage to /opt in the final image
EXPOSE 4443:4443
EXPOSE 8080:8080
# Set container working directory
# WORKDIR "/opt/picoquic"

# Add service-specific environment variables
ENV ROLE="server"
ENV UID=${UID}
ENV GID=${GID}
ENV SHADOW_TEST="1"

# # Copy logs and volumes
# VOLUME /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-12-07_21-59-43/Shadow_QUIC_Client-Server_Communication_Test/logs/picoquic_server:/app/logs
# # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/cert.pem:/opt/certs/cert.pem"
# # # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/key.pem:/opt/certs/key.pem"
# # # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/ticket.key"
# # 
# Define the command for the service
# TODO manage that in the Ivy module


FROM picoquic_shadow_rfc9000_panther:latest AS picoquic_client_stage

# Copy files from the service stage to /opt in the final image
EXPOSE 5000:5000
EXPOSE 8081:8081
# Set container working directory
# WORKDIR "/opt/picoquic"

# Add service-specific environment variables
ENV ROLE="client"
ENV UID=${UID}
ENV GID=${GID}
ENV SHADOW_TEST="1"

# # Copy logs and volumes
# VOLUME /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-12-07_21-59-43/Shadow_QUIC_Client-Server_Communication_Test/logs/picoquic_client:/app/logs
# # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/cert.pem:/opt/certs/cert.pem"
# # # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/certs/key.pem:/opt/certs/key.pem"
# # # # VOLUME "/home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/config/tls_keys:/opt/ticket/ticket.key"
# # 
# Define the command for the service
# TODO manage that in the Ivy module



# Final stage
FROM shadow_ns_v1_panther:latest
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root

COPY --from=picoquic_server_stage /opt /opt/picoquic_server
COPY --from=picoquic_client_stage /opt /opt/picoquic_client

COPY --from=shadow_ns_v1_panther /shadow /shadow
COPY --from=shadow_ns_v1_panther /root/.cargo/ /root/.cargo/
COPY --from=shadow_ns_v1_panther /root/.local/ /root/.local/
COPY --from=shadow_ns_v1_panther /usr/include/shadow.h /usr/include/shadow.h
COPY --from=shadow_ns_v1_panther /etc/shadow /etc/shadow

ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"
ENV PATH="/shadow/build:/root/shadow/build/:${PATH}"
RUN rustup default stable
RUN rm -rf shadow.data/
# VOLUME /home/crochetch/Documents/Projects/VerificationQUIC/PANTHER-SCP/panther/outputs/experiment_2024-12-07_21-59-43/Shadow_QUIC_Client-Server_Communication_Test/logs/shadow.data:/shadow.data

ADD shadow_ns.generated.yml /shadow_ns_config.yml
ENV RUST_BACKTRACE=1
# ENTRYPOINT [ "/bin/sh", "-l", "-c", "\" \"" ]
# ENTRYPOINT [ "shadow", "/shadow_ns_config.yml", "--data-directory", "/app/logs/shadow.data" ]
# CMD [ ">", "/app/logs/shadow_output.log" ]
ENTRYPOINT [ "/bin/sh", "-c", "shadow /shadow_ns_config.yml --data-directory /app/logs/shadow.data > /app/logs/shadow_stdout.log 2> /app/logs/shadow_stderr.log" ]
