ARG image

FROM $image:latest

# ADD panther/panther_worker/app/implementations/quic-implementations/picoquic /app/implementations/quic-implementations/picoquic

WORKDIR /app/implementations/quic-implementations

RUN rm -r /app/implementations/quic-implementations/picotls

RUN cd /app/implementations/quic-implementations/; git clone https://github.com/h2o/picotls.git && cd picotls && git checkout a1769991c69e4f9b8e3d19db5cce745aaa86b271 && git submodule init && git submodule update && cmake . && make && make check
 

RUN git clone https://github.com/private-octopus/picoquic.git

WORKDIR /app/implementations/quic-implementations/picoquic/
RUN git checkout 42c6200fb20217e31c07b2c3ac73dadbd0c337b8 
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /app
