from abc import ABC

from omegaconf import OmegaConf

from panther.core.observer.event_manager import EventManager
from panther.config.config_experiment_schema import TestConfig
from panther.config.config_global_schema import GlobalConfig
from panther.plugins.environments.execution_environment.memcheck.config_schema import (
    MemcheckConfig,
)
from panther.plugins.environments.execution_environment.execution_environment_interface import (
    IExecutionEnvironment,
)
from panther.plugins.plugin_loader import PluginLoader
from panther.plugins.services.services_interface import IServiceManager


class MemcheckEnvironment(IExecutionEnvironment, ABC):
    """
    MemcheckEnvironment provides an execution environment for running services under Valgrind's Memcheck tool.
    This class is responsible for configuring and setting up the environment to perform memory checking on services,
    using Valgrind's Memcheck. It manages the environment configuration, service managers, test and global configurations,
    and integrates with an event manager and plugin loader.
    Attributes:
        global_config (GlobalConfig): The global configuration for the environment.
        env_config_to_test (MemcheckConfig): The specific Memcheck configuration to use for testing.
        services_managers (list[IServiceManager]): List of service managers to be managed in this environment.
        test_config (TestConfig): The test configuration for the current test run.
        plugin_loader (PluginLoader): Loader for plugins used in the environment.
    Methods:
        __init__(env_config_to_test, output_dir, env_type, env_sub_type, event_manager):
            Initializes the MemcheckEnvironment with the provided configuration and managers.
        setup_environment(services_managers, test_config, global_config, timestamp, plugin_loader):
            Sets up the environment by configuring service managers, test and global configurations, and plugin loader.
            Also prepares the services to run under Memcheck.
        to_command(pid=None) -> str:
            Generates the Valgrind Memcheck command string to be used for running or attaching to a process.
        __repr__():
            Returns a string representation of the MemcheckEnvironment instance.
    """

    def __init__(
        self,
        env_config_to_test: MemcheckConfig,
        output_dir: str,
        env_type: str,
        env_sub_type: str,
        event_manager: EventManager,
    ):
        """
        Initializes the Memcheck environment with the provided configuration and parameters.

        Args:
            env_config_to_test (MemcheckConfig): The configuration object for the environment to be tested.
            output_dir (str): The directory where output files will be stored.
            env_type (str): The type of the environment.
            env_sub_type (str): The subtype of the environment.
            event_manager (EventManager): The event manager instance for handling events.
        """
        super().__init__(env_config_to_test, output_dir, env_type, env_sub_type, event_manager)
        self.global_config = None
        self.env_config_to_test = env_config_to_test

    def setup_environment(
        self,
        services_managers: list[IServiceManager],
        test_config: TestConfig,
        global_config: GlobalConfig,
        timestamp: str,
        plugin_loader: PluginLoader,
    ):
        """
        Sets up the execution environment for the test by configuring service managers and logging configuration details.

        Args:
            services_managers (list[IServiceManager]): List of service manager instances to be configured.
            test_config (TestConfig): The test-specific configuration object.
            global_config (GlobalConfig): The global configuration object.
            timestamp (str): Timestamp string for the current test run.
            plugin_loader (PluginLoader): Loader for managing plugins.

        Side Effects:
            - Updates each service manager's `run_cmd` dictionary by appending the command generated by `self.to_command()` to the "pre_run_cmds" list.
            - Logs detailed configuration and command information for debugging purposes.
            - Sets instance attributes for later use.
        """
        self.services_managers: list[IServiceManager] = services_managers
        self.test_config = test_config
        self.plugin_loader = plugin_loader
        self.global_config = global_config
        self.logger.debug("Setup environment with:")
        self.logger.debug("Services config: %s", self.env_config_to_test)
        for service in self.services_managers:
            self.logger.debug("Service cmds: %s", service.run_cmd)
            service.run_cmd["pre_run_cmds"] = service.run_cmd["pre_run_cmds"] + [self.to_command()]
            self.logger.debug("Service cmds: %s", service.run_cmd)

        self.logger.debug("Test Config: %s", OmegaConf.to_yaml(self.test_config))
        self.logger.debug("Global Config: %s", OmegaConf.to_yaml(self.global_config))

    def to_command(self, pid: int | None = None) -> str:
        """
        Generate the Valgrind Memcheck command for execution.
        :param pid: Optional process ID to attach to.
        :return: Valgrind Memcheck command as a string.
        """
        self.env_config_to_test = MemcheckConfig()
        command = [
            "valgrind",
            "--tool=memcheck",
            "--leak-check=full",
            "--track-origins=yes",
            "--show-leak-kinds=all",
        ]
        return " ".join(command)

    def __repr__(self):
        return (
            f"MemcheckEnvironment(env_config_to_test={self.env_config_to_test}, "
            f"output_dir={self.output_dir}, event_manager={self.event_manager}, "
            f"services_managers={self.services_managers}, test_config={self.test_config})"
        )