tests:
  - name: "QUIC Basic Connectivity Test"
    description: "Verify that the Picoquic client can connect to the server."
    protocol: "QUIC"
    environment: "DockerCompose"
    services:
      - name: "PicoquicServer"
        implementation: "picoquic"
        instances: 1
        parameters:
          role: "server"
      - name: "PicoquicClient"
        implementation: "picoquic"
        instances: 1
        parameters:
          role: "client"
    clients:
      - name: "LoadTester"
        implementation: "picoquic"
        parameters:
          role: "client"
    steps:
      wait:
        duration: 10  # seconds to wait during the test
    assertions:
      - type: "service_responsive"
        service: "PicoquicServer"
        endpoint: "4443/health"
        expected_status: 200
