#lang ivy1.7
include order
include file
include apt_shim 

#################################################
# Man in the Middle related parameters
#################################################

parameter mim_addr     : ip.addr = 0x0a000002
parameter mim_port_in  : ip.port = 4440 # One socket for receving 4440
parameter mim_port_out : ip.port = 4439 # One socket for sending

parameter is_mim            : bool = false
parameter is_mim_standalone : bool = false

parameter forward_packets   : bool = true
parameter keep_coalesed     : bool = true
parameter forward_packets_target : bool = false
parameter modify_packets    : bool = false
parameter replay_packets    : bool = false

parameter save_packet       : bool = false

instance mim_agent          : endpoint.mim_ep(mim_addr,mim_port_in,mim_port_out) 

# TODO instance for each type of endpoint or make more generic ?
instance mim_server_target : endpoint.server_quic(server_addr,server_port)
instance mim_client_target : endpoint.client_quic(0,0)
instance fake_client       : endpoint.client_quic(0,0)

var sock_mim_server : net.socket
var sock_mim_client : net.socket

var forged_packet_send : bool
after init {
    forged_packet_send := false;
}

#################################################
# Attacker related parameters
#################################################

parameter malicious_client_addr : ip.addr = 0x0a000003
parameter malicious_client_port : ip.port = 4441

parameter is_scanning         : bool = true
parameter start_scanning_port : ip.port = 4442
parameter end_scanning_port   : ip.port = 4443
parameter scanning_interval   : int = 1
parameter scanning_timeout    : int = 1
parameter scanning_timeout_max: int = 10
parameter scanning_timeout_min: int = 1
parameter scanning_timeout_step: int = 1
parameter scanning_timeout_max_retries: int = 3
parameter scanning_timeout_min_retries: int = 1
parameter scanning common_ports : bool = true

instance attacker : endpoint.attacker_ep(malicious_client_addr,malicious_client_port)
