#lang ivy1.7

include order
include ping_file
include ping_shim_client
include ivy_ping_client_behavior

after init {
    call time_api.c_timer.start;
}

after init {
    sock := net.open(endpoint_id.client,client.ep);
    client.set_tls_id(0);
    server.set_tls_id(1);
}

# export ping_event
export quic_frame.ping.handle
export quic_frame.timestamp.handle
export ping_packet_event
export client_send_event

export action _finalize = {
    # 
}