ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD miniP.h ping-pong-fail/miniP.h
ADD delay.h ping-pong-fail/delay.h
ADD delay_fail.h ping-pong-fail/delay_fail.h
ADD miniP_client.c ping-pong-fail/miniP_client.c
ADD miniP_server_fail.c ping-pong-fail/miniP_server_fail.c

RUN cd ping-pong-fail/; gcc miniP_client.c -o miniP_client && gcc miniP_server_fail.c -o miniP_server

WORKDIR /app