ARG image

FROM $image:latest

ADD src/implementations/coap-implementations/libcoap /PFV/implementations/coap-implementations/libcoap

RUN /bin/sh -c 'apt-get update && apt-get install -y autoconf automake gcc clang   libtool libtool-bin make pkg-config libcunit1-dev libssl-dev   libgnutls28-dev libmbedtls-dev exuberant-ctags git valgrind   graphviz doxygen libxml2-utils xsltproc docbook-xml docbook-xsl asciidoc'


ENV libcoap_dir=/PFV/implementations/coap-implementations/libcoap
# ADD . $libcoap_dir
WORKDIR /PFV/implementations/coap-implementations/libcoap

RUN ./autogen.sh --clean && ./autogen.sh