name: .
# When no services are provided, a placeholder service is used
services:
  ivy_server:
    image: panther_ivy_rfc9000:latest
    container_name: ivy_server
    stop_grace_period: 30s
    ports:
      - "4443:4443"
      - "4987:4987"
      - "8080:8080"
    environment:
      ROLE: server
      SSLKEYLOGFILE: "/app/logs/sslkeylogfile.txt"
      UID: "${UID}"
      GID: "${GID}"
    tty: true
    stdin_open: true
    hostname: ivy_server
    domainname: panther.local
    # TODO fix in the docker
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    working_dir: "/app"
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x /app/entrypoint.sh \
        && exec /app/entrypoint.sh

    # TODO fix sudo tshark
    volumes:
      - /Users/elniak/Documents/Project/PANTHER/logs/ivy_server:/app/logs/
      - /Users/elniak/Documents/Project/PANTHER/entrypoint_ivy_server.sh:/app/entrypoint.sh
      - "/Users/elniak/Documents/Project/PANTHER/panther/plugins/services/testers/panther_ivy/ivy/include/1.7:/opt/panther_ivy/ivy/include/1.7"
      - "/Users/elniak/Documents/Project/PANTHER/panther/plugins/services/testers/panther_ivy/protocol-testing/quic:/opt/panther_ivy/protocol-testing/quic/"
      - "shared_logs:/app/sync_logs"
    networks:
      panther_network:
        aliases:
          - ivy_server
  picoquic_client:
    image: picoquic_rfc9000:latest
    container_name: picoquic_client
    stop_grace_period: 30s
    ports:
      - "5000:5000"
      - "8081:8081"
    environment:
      ROLE: client
      SSLKEYLOGFILE: "/app/logs/sslkeylogfile.txt"
      UID: "${UID}"
      GID: "${GID}"
    tty: true
    stdin_open: true
    hostname: picoquic_client
    domainname: panther.local
    # TODO fix in the docker
    cap_add:
      - CAP_NET_ADMIN
      - CAP_NET_RAW
    working_dir: "/opt/picoquic"
    entrypoint:
      - /bin/sh
      - -c
      - |
        chmod +x /app/entrypoint.sh \
        && exec /app/entrypoint.sh

    # TODO fix sudo tshark
    volumes:
      - /Users/elniak/Documents/Project/PANTHER/logs/picoquic_client:/app/logs/
      - /Users/elniak/Documents/Project/PANTHER/entrypoint_picoquic_client.sh:/app/entrypoint.sh
    networks:
      panther_network:
        aliases:
          - picoquic_client

networks:
  panther_network:
    driver: bridge

volumes:
  shared_logs:
    driver: local