version: 1.0.{build}

before_build:
  - cmake -DLSQPACK_TESTS=ON .

build_script:
  - cmake --build .

before_test:
  - set PATH=%PATH%;c:\projects\ls-qpack\bin\Debug

test_script:
  - dir
  - msbuild RUN_TESTS.vcxproj 
