FROM localhost_single_container_v1_panther:latest AS shadow_base

{% for service in services %}
FROM {{ service.implementation_name }}_{{ service.service_protocol.version.name }}_panther:latest AS {{ service.service_name }}_stage

# Copy files from the service stage to /opt in the final image
{% for port in service.service_config_to_test.ports %}
EXPOSE {{ port }}
{% endfor %}

# Set container working directory
# WORKDIR "{{ service.run_cmd["run_cmd"]["working_dir"] }}"

# Add service-specific environment variables
ENV ROLE="{{ service.role }}"
ENV UID=${UID}
ENV GID=${GID}
{% for key, value in service.environments.items() %}
ENV {{ key }}="{{ value }}"
{% endfor %}

# Define the command for the service
RUN <<EOF
echo "Running pre-compilation commands:"
{% for cmd in service.run_cmd["pre_compile_cmds"] %}
{{ cmd }}
{% endfor %}
EOF

RUN <<EOF
echo "Running compilation commands:"
{% for cmd in service.run_cmd["compile_cmds"] %}
{{ cmd }}
{% endfor %}
EOF
{% endfor %}

# Final stage
FROM localhost_single_container_v1_panther:latest
WORKDIR /
ENV DEBIAN_FRONTEND=noninteractive
USER root

{% for service in services %}
{% if "ivy" in service.service_name %}
COPY --from={{ service.service_name }}_stage /usr/local/lib/python3.10 /usr/local/lib/python3.10
COPY --from={{ service.service_name }}_stage /opt /opt
{% else %}
COPY --from={{ service.service_name }}_stage /opt /opt/{{ service.service_name }}
{% endif %}
{% endfor %}

USER root

# TODO try to install the packages in the base image and keep them in the final image
RUN apt-get update && \
    apt-get install -y build-essential git cmake software-properties-common \
    openssl libssl-dev pkg-config clang python3 net-tools tcpdump \
    apt-utils  wireshark tshark  libcap2-bin traceroute \
    iputils-ping iproute2 iperf3 netcat-openbsd curl dnsutils iperf 
RUN yes yes | DEBIAN_FRONTEND=teletype dpkg-reconfigure wireshark-common

ARG USER_UID=1000
ARG USER_GID=1000
ARG USER_N=elniak

RUN addgroup --gid ${USER_GID} ${USER_N} && \
    adduser --disabled-password --gecos '' --uid ${USER_UID} --gid ${USER_GID} ${USER_N} && \
    usermod -aG wireshark ${USER_N}

ENV PATH="/root/.local/bin:/root/.cargo/bin:${PATH}"

ADD {{ localhost_single_container_config_file }} /run.sh
ENV RUST_BACKTRACE=1
RUN chmod +x /run.sh
ENTRYPOINT [ "/bin/sh", "-c", "./run.sh > /app/logs/localhost_stdout.log 2> /app/logs/localhost_stderr.log; {% for service in services %}{% if not test_config.services[service.service_name].implementation.type.name == "testers" %}{% set replacement_path = '/opt/' ~ service.service_name ~ '/' %}{% else %}{% set replacement_path = '/opt/'%}{% endif %}{% for cmd in service.run_cmd["post_run_cmds"] %}{{ cmd | replace("\n", "") | replace('/opt/', replacement_path) | replace("/app/logs/", "/app/logs/" ~ service.service_name ~ "/") }}{% endfor -%}{% endfor -%}" ]

