ARG image

FROM $image:latest

ADD src/implementations/bgp-implementations/gobgp /PFV/implementations/bgp-implementations/gobgp

WORKDIR /PFV/implementations/bgp-implementations/gobgp/


#Install go
RUN wget https://dl.google.com/go/go1.16.linux-amd64.tar.gz  &> /dev/null; \
         rm -r /go; \
         tar xfz go1.16.linux-amd64.tar.gz &> /dev/null \
         rm go1.16.linux-amd64.tar.gz
ENV PATH="/go/bin:${PATH}"

RUN go mod download