ARG image

FROM $image:latest

# ADD panther/panther_worker/implementations/quic-implementations/picotls /app/implementations/quic-implementations/picotls

WORKDIR /app/implementations/quic-implementations

RUN git clone https://github.com/h2o/picotls.git 

WORKDIR /app/implementations/quic-implementations/picotls
ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl

RUN apt-get install libssl-dev -y
# 47327f8d032f6bc2093a15c32e666ab6384ecca2
RUN git checkout 047c5fe20bb9ea91c1caded8977134f19681ec76 
RUN git submodule init
RUN git submodule update
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check

WORKDIR /app

