"""Output collector interface for gathering test outputs.

This module defines the interface for collecting outputs from execution environments.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict


class IOutputCollector(ABC):
    """Interface for execution environment output collection.

    Implementing classes provide output discovery and metadata for the
    `OutputAggregator` to collect artifacts from diverse environment types
    (Docker Compose, localhost, Shadow NS).

    Implementations must provide:
        1. `collect_outputs()`: returns paths to all generated artifacts.
        2. `get_output_metadata()`: provides size, format, and timing info.

    Return empty dicts rather than raising exceptions for missing outputs.
    Include partial results when some outputs are unavailable.
    """

    @abstractmethod
    def collect_outputs(self) -> Dict[str, str]:
        """Collect all outputs generated by this execution environment.

        Returns:
            dict[str, str]: Dictionary mapping output type to file path
                           Example: {
                               "trace": "/path/to/trace.out",
                               "profile": "/path/to/profile.data",
                               "log": "/path/to/execution.log"
                           }
        """
        pass

    @abstractmethod
    def get_output_metadata(self) -> Dict[str, Any]:
        """Get metadata about the collected outputs.

        Returns:
            Dict[str, Any]: Metadata including size, format, timestamp, etc.
                           Example: {
                               "trace": {
                                   "size_bytes": 1024000,
                                   "format": "strace",
                                   "timestamp": "2024-01-01T12:00:00"
                               }
                           }
        """
        pass
