ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt/miniP.h ping-pong-mt/miniP.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt/delay.h ping-pong-mt/delay.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt/miniP_client.c ping-pong-mt/miniP_client.c
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt/miniP_server_mt_fonctionnel.c ping-pong-mt/miniP_server_mt_fonctionnel.c

RUN cd ping-pong-mt/; gcc miniP_client.c -o miniP_client && gcc miniP_server_mt_fonctionnel.c -o miniP_server -lpthread

WORKDIR /app