ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-fail/miniP.h ping-pong-fail/miniP.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-fail/delay.h ping-pong-fail/delay.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-fail/delay_fail.h ping-pong-fail/delay_fail.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-fail/miniP_client.c ping-pong-fail/miniP_client.c
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-fail/miniP_server_fail.c ping-pong-fail/miniP_server_fail.c

RUN cd ping-pong-fail/; gcc miniP_client.c -o miniP_client && gcc miniP_server_fail.c -o miniP_server

WORKDIR /app