ARG image

FROM $image:latest

WORKDIR /app/implementations/minip-implementations

ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt-flaky/miniP.h ping-pong-mt-flaky/miniP.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt-flaky/delay.h ping-pong-mt-flaky/delay.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt-flaky/delay_flaky.h ping-pong-mt-flaky/delay_flaky.h
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt-flaky/miniP_client.c ping-pong-mt-flaky/miniP_client.c
ADD pfv/pfv_worker/implementations/minip-implementations/ping-pong-mt-flaky/miniP_server_mt_flaky.c ping-pong-mt-flaky/miniP_server_mt_flaky.c

RUN cd ping-pong-mt-flaky/; gcc miniP_client.c -o miniP_client && gcc miniP_server_mt_flaky.c -o miniP_server -lpthread

WORKDIR /app