ARG image

FROM $image:latest

WORKDIR /

RUN wget https://go.dev/dl/go1.22.5.src.tar.gz  &> /dev/null
RUN tar xfz go1.22.5.src.tar.gz &> /dev/null
ENV PATH="/go/bin:${PATH}"

WORKDIR /app/implementations/quic-implementations/

# ADD panther/panther_worker/app/implementations/quic-implementations/boringssl /app/implementations/quic-implementations/boringssl
RUN git clone https://boringssl.googlesource.com/boringssl; cd boringssl; git checkout a9670a8b476470e6f874fef3554e8059683e1413; git submodule init; git submodule update

# ADD panther/panther_worker/app/implementations/quic-implementations/lsquic    /app/implementations/quic-implementations/lsquic
RUN git clone https://github.com/litespeedtech/lsquic.git;  cd lsquic;    git checkout 0a4f8953dc92dd3085e48ed90f293f052cff8427; git submodule update --init; 


# RUN git checkout a9670a8b476470e6f874fef3554e8059683e1413
# RUN git submodule init
# RUN git submodule update

RUN apt-get update 
RUN apt-get install -y build-essential software-properties-common \
                       zlib1g-dev libevent-dev golang

WORKDIR /app/implementations/quic-implementations/boringssl/
ENV PATH="/go/bin:${PATH}"
RUN cmake . &&  make
ENV BORINGSSL=/app/implementations/quic-implementations/boringssl/


WORKDIR /app/implementations/quic-implementations/lsquic/
# RUN git checkout 0a4f8953dc92dd3085e48ed90f293f052cff8427 # 639c9e685d37e74d357d3dd8599b9dbff90934af
COPY lsquic/rfc9000/lsquic_types.h /app/implementations/quic-implementations/lsquic/include/lsquic_types.h
RUN cmake -DBORINGSSL_DIR=$BORINGSSL .
RUN make
RUN make test || true

WORKDIR /app

