ARG image

FROM $image:latest

WORKDIR /

RUN wget https://go.dev/dl/go1.22.5.src.tar.gz  &> /dev/null
RUN tar xfz go1.22.5.src.tar.gz &> /dev/null
ENV PATH="/go/bin:${PATH}"

WORKDIR /app/implementations/quic-implementations/

RUN git clone https://boringssl.googlesource.com/boringssl boringssl-vuln;
RUN git clone https://github.com/litespeedtech/lsquic.git lsquic-vuln;  cd lsquic-vuln;     git submodule update --init; 


WORKDIR /app/implementations/quic-implementations/boringssl-vuln/
ENV PATH="/go/bin:${PATH}"
RUN git checkout a2278d4d2cabe73f6663e3299ea7808edfa306b9 # 47327f8d032f6bc2093a15c32e666ab6384ecca2
RUN git submodule init
RUN git submodule update

RUN apt-get update 
RUN apt-get install -y build-essential software-properties-common \
                       zlib1g-dev libevent-dev golang
RUN cmake . &&  make
ENV BORINGSSL=/app/implementations/quic-implementations/boringssl-vuln/


WORKDIR /app/implementations/quic-implementations/lsquic-vuln/
RUN git checkout v2.29.4 # 639c9e685d37e74d357d3dd8599b9dbff90934af
COPY lsquic/rfc9000/lsquic_types.h /app/implementations/quic-implementations/lsquic/include/lsquic_types.h
RUN git submodule update --init --recursive
RUN git submodule update --recursive
RUN cmake -DBORINGSSL_DIR=$BORINGSSL .
RUN make
RUN make test || true

WORKDIR /app

