# ARG image

# FROM $image:latest

# ADD pfv/pfv_worker/app/implementations/quic-implementations/picoquic /app/implementations/quic-implementations/picoquic

# ADD pfv/pfv_worker/app/implementations/quic-implementations/picoquic/
# RUN git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7 # 639c9e685d37e74d357d3dd8599b9dbff90934af
# COPY src/containers/res/picoquic/rfc9000/picoquic_internal.h  /app/implementations/quic-implementations/picoquic/picoquic/picoquic_internal.h
# RUN /usr/bin/cmake --version
# RUN /usr/bin/cmake .
# RUN make
# RUN ./picoquic_ct || true

# WORKDIR /app

ARG image

FROM $image:latest

WORKDIR /app/implementations/quic-implementations/

RUN rm -r /app/implementations/quic-implementations/picotls

RUN cd /app/implementations/quic-implementations/; git clone https://github.com/h2o/picotls.git && cd picotls && git checkout 7d294ab4f2e0ed749b4bcfaf533225a4e0c096f7 && git submodule init && git submodule update && cmake . && make && make check

RUN git clone https://github.com/ElNiak/picoquic.git &&  cd picoquic && git checkout master && /usr/bin/cmake . && make

WORKDIR /app

