#lang ivy1.7

include quic_types
include quic_transport_error_code
include quic_frame
include quic_transport_parameters
include ip
include quic_fsm_sending
include quic_fsm_receiving

#
# Forged UDP datagram
# ------------------

# This section defines the foged packet datatype. Forged UDP datagram are the basic
# unit of communication between endpoints and MiM agent. It consist in UDP headers 
# containing QUIC packet as payloads
# ### Packet

# The type `forged_datagram` represents forged UDP datagram. 

# The fields are:
#


object forged_datagram = {
    type this = struct {
        src_port : ip.port, # [2]
        dst_port : ip.port, # [3]
        checksum : stream_data, # [4]
        payload : packet.quic_packet # [8]
    }

    instance idx : unbounded_sequence
    instance arr : array(idx,this)
}

# Forged UDP datagram protocol events
# -----------------------

# The Forged UDP datagram event
# ================
#
# This event corresponds to transmission of a Forged UDP datagram containing QUIC packets.
#
# Parameters
# ----------
#
# - `src`: the source endpoint
# - `dst`: the destination endpoint
# - `pkt` : the packet contents

action forged_datagram_event(src:ip.endpoint,dst:ip.endpoint,pkt:forged_datagram) = {}

#action packet_event_multiple_src(src1:ip.endpoint,src2:ip.endpoint,dst:ip.endpoint,pkt:packet.quic_packet) = {}

# Packet protocol state
# ---------------------

# This section defines the history variables that track the state of
# the packet protocol. Some of these variables are shared between
# protocol layers, so that the allowed interleavings of events at
# different layers can be specified.
#

# Forged datagram protocol state
# ------------------------------

function forged_datagram_to_made : forged_datagram # associate src ?

# Packet event specification
# --------------------------

# A packet event represents the transmision of a QUIC packet `pkt`
# from source endpoint `src` to a QUIC destination endpoint `dst`
# containing a sequence of queued frames.
#
# ### Requirements
#


# ### Effects
#
   
#
# ### Notes
#

around forged_datagram_event(src:ip.endpoint,dst:ip.endpoint,pkt:forged_datagram) {
    # Before
    
    ...

    # Here, we have the updates to the packet protocol state.

  
}


# Procedures
# ==========    
