FROM ubuntu:20.04  

ADD ./app/ /app/

WORKDIR /app

# Install dependencies
ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get update
 
ADD setup.py .
RUN apt-get install -y python3-pip python3-dev python3-setuptools python3-wheel
RUN python3 -m pip install .

ENV PATH="/root/.cargo/bin:${PATH}"
WORKDIR /app