logging:
  level: DEBUG
  format: "%(asctime)s [%(levelname)s] - %(module)s - %(message)s"

paths:
  output_dir: "outputs"
  log_dir: "outputs/logs"
  config_dir: "panther/configs"
  plugin_dir: "panther/plugins"

docker:
  force_build_docker_image: True

tests:
  - name: "Minip Client-Server Random Communication Test"
    description: "Verify that the PingPong client can communicate with the PingPong server over Docker Compose network."
    network_environment:
      type: "docker_compose"  # Environment plugin name
    iterations: 1
    generate_new_certificates: True
    services:
      ping_pong_client:
        timeout: 100
        name: "ping_pong_client"  # Added 'name' key
        implementation:
          name: "ping_pong"
          type: "IUT"
        protocol:
          name: "minip"
          role: "client"
          version: "random"
          target: "ping_pong_server"  # Docker Compose service name
        ports:
          - "5000:5000"  # Example port if needed
          - "8081:8081"  # Changed to avoid port conflict
        generate_new_certificates: True

      ping_pong_server:
        name: "ping_pong_server"  # Added 'name' key
        timeout: 60
        implementation:
          type: "IUT"
          name: "ping_pong"
        protocol:
          name: "minip"
          version: "random"
          role: "server"
        ports:
          - "4443:4443"
          - "4987:4987"  #
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True

    steps:
      wait: 100  # seconds to wait during the test

  - name: "Shadow Minip Client-Server Functional Communication Test"
    description: "Verify that the PingPong client can communicate with the PingPong server over Shadow network."
    network_environment:
      type: "shadow_ns"  # Environment plugin name
      general:
        stop_time: 100
        model_unblocked_syscall_latency: false
      experimental:
        strace_logging_mode: "standard"
      network:
        latency: 10
        jitter: 10
        packet_loss: 0.0
      host_option_defaults:
        pcap_enabled: true
    iterations: 1
    generate_new_certificates: True
    services:
      ping_pong_client:
        timeout: 100
        name: "ping_pong_client"  # Added 'name' key
        implementation:
          name: "ping_pong"
          type: "IUT"
        protocol:
          name: "minip"
          role: "client"
          version: "functional"
          target: "ping_pong_server"  # Docker Compose service name
        ports:
          - "5000:5000"  # Example port if needed
          - "8081:8081"  # Changed to avoid port conflict
        generate_new_certificates: True

      ping_pong_server:
        name: "ping_pong_server"  # Added 'name' key
        timeout: 60
        implementation:
          type: "IUT"
          name: "ping_pong"
        protocol:
          name: "minip"
          version: "functional"
          role: "server"
        ports:
          - "4443:4443"
          - "4987:4987"  #
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True

    steps:
      wait: 100  # seconds to wait during the test
