#lang ivy1.7

action make_transport_parameters returns (tp:quic_transport_parameters) = {
    var imsdbl : initial_max_stream_data_bidi_local;
    imsdbl.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    var imd : initial_max_data;
    imd.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    var it : max_idle_timeout;
    it.seconds_16 := random_microsecs(0,0xFFFFFFF);
    var imsdbr : initial_max_stream_data_bidi_remote;
    imsdbr.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    var imsdu : initial_max_stream_data_uni;
    imsdu.stream_pos_32 := random_stream_pos(1,0xFFFFFFF);
    tp.transport_parameters := tp.transport_parameters.append(imsdbl);
    tp.transport_parameters := tp.transport_parameters.append(imd);
    tp.transport_parameters := tp.transport_parameters.append(it);
    tp.transport_parameters := tp.transport_parameters.append(imsdbr);
    tp.transport_parameters := tp.transport_parameters.append(imsdu);
    # TEMPORARY: a missing numeric parameter should be treated as zero,
    # but some clients don't handle this correctly, so we put all parameters in.
    # Remove the following to test this client behavior.
    var imsib : initial_max_stream_id_bidi;
    imsib.stream_id_16 := initial_max_streams_bidi;
    tp.transport_parameters := tp.transport_parameters.append(imsib);
    
    #if client_non_zero_scil {
    var icid : initial_source_connection_id; #update v29
    icid.scid := the_cid+1;
    tp.transport_parameters := tp.transport_parameters.append(icid);
    #};
    var odci : original_destination_connection_id; #update v29
    odci.dcid := client_initial_dcid+1;
    tp.transport_parameters := tp.transport_parameters.append(odci);

    var max_streams_uni : initial_max_stream_id_uni; #TODO update v29
    max_streams_uni.stream_id_16 := random_stream_id(4,0xFFFFFFF);
    tp.transport_parameters := tp.transport_parameters.append(max_streams_uni);

    # var max_ack_dela : max_ack_delay; #TODO update rfc9000
    # max_ack_dela.exponent_8 := random_microsecs(4,0xFFFFFFF);
    # tp.transport_parameters := tp.transport_parameters.append(max_ack_dela);

    var max_packet_z : max_packet_size; #TODO update v29
    max_packet_z.stream_pos_16 := 1500;
    tp.transport_parameters := tp.transport_parameters.append(max_packet_z);
}