#lang ivy1.7

include c_time

object time_api = {
    instance c_timer : c_time(microseconds, milliseconds,seconds)
}    

function sleep_start:milliseconds
relation slept

action milliseconds_to_microseconds(delay:milliseconds) returns (scaled:microseconds) = {
   <<<
    scaled = delay * 1000;
   >>> 
}

action microseconds_to_milliseconds(delay:microseconds) returns (scaled:milliseconds) = {
   <<<
    scaled = delay/1000;
   >>> 
}