#lang ivy1.7

include order
include quic_infer
include file
include quic_shim
# include quic_locale
include random_value

# create a client and server. the client has an instance of TLS

# instance client : quic_endpoint(endpoint_id.client)
# instance server : quic_endpoint(endpoint_id.server)

instance attacker : quic_endpoint.attacker_ep(client_addr,client_port)

# We create sockets and bind them to the addresses that the client can use.

# TODO create socket for client & server
# TODO associate these data to the entities itself
var sock_attacker : net.socket


