logging:
  level: DEBUG
paths:
  output_dir: "outputs"
  plugin_dir: "panther/plugins"
docker:
  force_build_docker_image: false
  no_docker_cache: true
  use_buildx: true
  target_platform: linux/amd64
tests:
  - name: "BGP Session Establishment (Accept)"
    network_environment:
      type: docker_compose
    iterations: 1
    steps:
      wait: 120
    services:
      frr_server:
        name: frr_server
        timeout: 180
        implementation:
          name: frr_bgp
          type: iut
        protocol:
          name: bgp
          version: rfc4271
          role: server
        ports:
          - "179:179"
      ivy_tester:
        name: ivy_tester
        timeout: 180
        implementation:
          name: panther_ivy
          type: testers
          test: bgp_speaker_test_accept
          z3_source: pip
          log_level_events: DEBUG
          log_level_binary: DEBUG
          optimization_level: O0
          iterations_per_test: 1
          internal_iterations_per_test: 100
        protocol:
          name: bgp
          version: rfc4271
          role: client
          target: frr_server

  - name: "BGP Session Establishment (Join)"
    network_environment:
      type: docker_compose
    iterations: 1
    steps:
      wait: 120
    services:
      frr_server:
        name: frr_server
        timeout: 180
        implementation:
          name: frr_bgp
          type: iut
        protocol:
          name: bgp
          version: rfc4271
          role: server
        ports:
          - "179:179"
      ivy_tester:
        name: ivy_tester
        timeout: 180
        implementation:
          name: panther_ivy
          type: testers
          test: bgp_speaker_test_join
          z3_source: pip
          log_level_events: DEBUG
          log_level_binary: DEBUG
          optimization_level: O0
          iterations_per_test: 1
          internal_iterations_per_test: 100
        protocol:
          name: bgp
          version: rfc4271
          role: client
          target: frr_server

  - name: "BGP UPDATE Compliance"
    network_environment:
      type: docker_compose
    iterations: 1
    steps:
      wait: 120
    services:
      frr_server:
        name: frr_server
        timeout: 180
        implementation:
          name: frr_bgp
          type: iut
        protocol:
          name: bgp
          version: rfc4271
          role: server
        ports:
          - "179:179"
      ivy_tester:
        name: ivy_tester
        timeout: 180
        implementation:
          name: panther_ivy
          type: testers
          test: bgp_speaker_test_update
          z3_source: pip
          log_level_events: DEBUG
          log_level_binary: DEBUG
          optimization_level: O0
          iterations_per_test: 1
          internal_iterations_per_test: 100
        protocol:
          name: bgp
          version: rfc4271
          role: client
          target: frr_server

  - name: "BGP Error Handling (Cease)"
    network_environment:
      type: docker_compose
    iterations: 1
    steps:
      wait: 120
    services:
      frr_server:
        name: frr_server
        timeout: 180
        implementation:
          name: frr_bgp
          type: iut
        protocol:
          name: bgp
          version: rfc4271
          role: server
        ports:
          - "179:179"
      ivy_tester:
        name: ivy_tester
        timeout: 180
        implementation:
          name: panther_ivy
          type: testers
          test: bgp_speaker_test_error
          z3_source: pip
          log_level_events: DEBUG
          log_level_binary: DEBUG
          optimization_level: O0
          iterations_per_test: 1
          internal_iterations_per_test: 100
        protocol:
          name: bgp
          version: rfc4271
          role: client
          target: frr_server
