logging:
  level: INFO
paths:
  output_dir: "outputs"
  plugin_dir: "panther/plugins"
docker:
  force_build_docker_image: false
  use_buildx: true
tests:
  - name: "BGP Session Establishment (Join)"
    network_environment:
      type: docker_compose
    iterations: 1
    services:
      frr_router:
        name: frr_router
        timeout: 60
        implementation:
          name: frr_bgp
          type: iut
        protocol:
          name: bgp
          version: rfc4271
          role: server
        ports:
          - "179:179"
      ivy_tester:
        name: ivy_tester
        timeout: 120
        implementation:
          name: panther_ivy
          type: testers
          test: bgp_speaker_test_join
        protocol:
          name: bgp
          version: rfc4271
          role: client
          target: frr_router
