logging:
  level: DEBUG
  format: "%(asctime)s [%(levelname)s] - %(module)s - %(message)s"
  
paths:
  output_dir: "outputs"
  log_dir: "outputs/logs"
  config_dir: "panther/configs"
  plugin_dir: "panther/plugins"

docker:
  build_docker_image: True
 
tests:
  - name: "QUIC IvyServer-Client Communication Test "
    description: "Verify that the Picoquic server can communicate with the Ivy-Tester client over Docker Compose network."
    network_environment: 
      type: "docker_compose" 
      # should_no_be_ignore : "should_no_be_ignore"
    execution_environment: 
      - type: "helgrind"
    iterations: 1
    should_be_ignore : "should_be_ignore"
    services:
      # should_no_be_ignore : "should_no_be_ignore"
      picoquic_client:
        name: "picoquic_client" 
        timeout: 150
        implementation: 
          name: "picoquic" # parameters are presents in folder plugins/services/implementations/quic/picoquic/config.yaml
          type: "iut" # plugin is present plugins/services/iut/quic/picoquic
          # should_no_be_ignore : "should_no_be_ignore"
        protocol: # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "client"
          target: "ivy_server"  # Docker Compose service name
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True
        should_be_ignore : "should_be_ignore"
          
      ivy_server:
        name: "ivy_server"  # Added 'name' key
        timeout: 150
        implementation: 
          name: "panther_ivy"
          type: "testers" # plugin is present plugins/services/testers/panther_ivy
          test: quic_client_test_max
        # TODO: we should be able to validate that quic_server_test_stream is available for the selected protocol and role
        protocol:  # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "server"
          target: "picoquic_client"  # Docker Compose service name
        ports:
          - "5000:5000"  
          - "4987:4987"  
          - "8081:8081"  
        generate_new_certificates: True
    steps:
      wait: 150  # seconds to wait during the test

  - name: "QUIC IvyClient-Server Communication Test - Strace"
    description: "Verify that the Picoquic server can communicate with the Ivy-Tester client over Docker Compose network."
    network_environment: 
      type: "docker_compose" 
      # should_no_be_ignore : "should_no_be_ignore"
    execution_environment: 
      - type: "helgrind"  
    iterations: 1
    should_be_ignore : "should_be_ignore"
    services:
      # should_no_be_ignore : "should_no_be_ignore"
      picoquic_server:
        name: "picoquic_server" 
        timeout: 150
        implementation: 
          name: "picoquic" # parameters are presents in folder plugins/services/implementations/quic/picoquic/config.yaml
          type: "iut" # plugin is present plugins/services/iut/quic/picoquic
          # should_no_be_ignore : "should_no_be_ignore"
        protocol: # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "server"
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True
        should_be_ignore : "should_be_ignore"
          
      ivy_client:
        name: "ivy_client"  # Added 'name' key
        timeout: 150
        implementation: 
          name: "panther_ivy"
          type: "testers" # plugin is present plugins/services/testers/panther_ivy
          test: quic_server_test_stream
        # TODO: we should be able to validate that quic_server_test_stream is available for the selected protocol and role
        protocol:  # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "client"
          target: "picoquic_server"  # Docker Compose service name
        ports:
          - "5000:5000"  
          - "4987:4987"  
          - "8081:8081"  
        generate_new_certificates: True
    steps:
      wait: 150  # seconds to wait during the test

  - name: "QUIC IvyServer-Client Communication Test - Use System Models"
    description: "Verify that the Picoquic server can communicate with the Ivy-Tester client over Docker Compose network."
    network_environment: 
      type: "docker_compose" 
      # should_no_be_ignore : "should_no_be_ignore"
    execution_environment: 
      - type: "helgrind"
    iterations: 1
    should_be_ignore : "should_be_ignore"
    services:
      # should_no_be_ignore : "should_no_be_ignore"
      picoquic_client:
        name: "picoquic_client" 
        timeout: 150
        implementation: 
          name: "picoquic" # parameters are presents in folder plugins/services/implementations/quic/picoquic/config.yaml
          type: "iut" # plugin is present plugins/services/iut/quic/picoquic
          # should_no_be_ignore : "should_no_be_ignore"
        protocol: # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "client"
          target: "ivy_server"  # Docker Compose service name
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True
        should_be_ignore : "should_be_ignore"
          
      ivy_server:
        name: "ivy_server"  # Added 'name' key
        timeout: 150
        implementation: 
          name: "panther_ivy"
          type: "testers" # plugin is present plugins/services/testers/panther_ivy
          test: quic_client_test_max
          use_system_models: True
        # TODO: we should be able to validate that quic_server_test_stream is available for the selected protocol and role
        protocol:  # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "server"
          target: "picoquic_client"  # Docker Compose service name
        ports:
          - "5000:5000"  
          - "4987:4987"  
          - "8081:8081"  
        generate_new_certificates: True
    steps:
      wait: 150  # seconds to wait during the test

  - name: "QUIC IvyClient-Server Communication Test - Strace - use_system_models"
    description: "Verify that the Picoquic server can communicate with the Ivy-Tester client over Docker Compose network."
    network_environment: 
      type: "docker_compose" 
      # should_no_be_ignore : "should_no_be_ignore"
    execution_environment: 
      - type: "helgrind"  
    iterations: 1
    should_be_ignore : "should_be_ignore"
    services:
      # should_no_be_ignore : "should_no_be_ignore"
      picoquic_server:
        name: "picoquic_server" 
        timeout: 150
        implementation: 
          name: "picoquic" # parameters are presents in folder plugins/services/implementations/quic/picoquic/config.yaml
          type: "iut" # plugin is present plugins/services/iut/quic/picoquic
          # should_no_be_ignore : "should_no_be_ignore"
        protocol: # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "server"
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True
        should_be_ignore : "should_be_ignore"
          
      ivy_client:
        name: "ivy_client"  # Added 'name' key
        timeout: 150
        implementation: 
          name: "panther_ivy"
          type: "testers" # plugin is present plugins/services/testers/panther_ivy
          test: quic_server_test_stream
          use_system_models: True
        # TODO: we should be able to validate that quic_server_test_stream is available for the selected protocol and role
        protocol:  # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "client"
          target: "picoquic_server"  # Docker Compose service name
        ports:
          - "5000:5000"  
          - "4987:4987"  
          - "8081:8081"  
        generate_new_certificates: True
    steps:
      wait: 150  # seconds to wait during the test
  
  # - name: "Gperf CPU and Strace - QUIC Client-IvyServer Communication Test"
  #   description: "Verify that the Picoquic client can communicate with the Picoquic server over Docker Compose network."
  #   network_environment: 
  #     type: "docker_compose"  # Environment plugin name
  #   iterations: 1
  #   execution_environment: 
  #     - type: "gperf_cpu"
  #     - type: "strace"  
  #   generate_new_certificates: True
  #   services:
  #     picoquic_client:
  #       timeout: 300
  #       name: "picoquic_client"  # Added 'name' key
  #       implementation: 
  #         name: "picoquic"
  #         type: "iut"
  #       protocol:
  #         name: "quic"
  #         version: "rfc9000"
  #         role: "client"
  #         target: "ivy_server"  # Docker Compose service name
  #       ports:
  #         - "5000:5000"  # Example port if needed
  #         - "8081:8081"  # Changed to avoid port conflict
  #       generate_new_certificates: True

  #     ivy_server:
  #       name: "ivy_server"  # Added 'name' key
  #       timeout: 60
  #       implementation: 
  #         type: "testers"
  #         name: "panther_ivy"
  #         test: quic_client_test_max
  #       protocol:
  #         name: "quic"
  #         version: "rfc9000"
  #         role: "server"
  #       ports:
  #         - "4443:4443"
  #         - "4987:4987"  #
  #         - "8080:8080"  # Health check endpoint
  #       generate_new_certificates: True

  #   steps:
  #     wait: 300  # seconds to wait during the test

  # - name: "Heap QUIC Client-IvyServer Communication Test"
  #   description: "Verify that the Picoquic client can communicate with the Picoquic server over Docker Compose network."
  #   network_environment: 
  #     type: "docker_compose"  # Environment plugin name
  #   iterations: 1
  #   execution_environment: 
  #     - type: "gperf_heap"
  #   generate_new_certificates: True
  #   services:
  #     picoquic_client:
  #       timeout: 300
  #       name: "picoquic_client"  # Added 'name' key
  #       implementation: 
  #         name: "picoquic"
  #         type: "iut"
  #       protocol:
  #         name: "quic"
  #         version: "rfc9000"
  #         role: "client"
  #         target: "ivy_server"  # Docker Compose service name
  #       ports:
  #         - "5000:5000"  # Example port if needed
  #         - "8081:8081"  # Changed to avoid port conflict
  #       generate_new_certificates: True

  #     ivy_server:
  #       name: "ivy_server"  # Added 'name' key
  #       timeout: 60
  #       implementation: 
  #         type: "testers"
  #         name: "panther_ivy"
  #         test: quic_client_test_max
  #       protocol:
  #         name: "quic"
  #         version: "rfc9000"
  #         role: "server"
  #       ports:
  #         - "4443:4443"
  #         - "4987:4987"  #
  #         - "8080:8080"  # Health check endpoint
  #       generate_new_certificates: True

  #   steps:
  #     wait: 300  # seconds to wait during the test

  # - name: "Minip Client-Server Random Communication Test"
  #   description: "Verify that the PingPong client can communicate with the PingPong server over Docker Compose network."
  #   network_environment: 
  #     type: "docker_compose"  # Environment plugin name
  #   iterations: 1
  #   generate_new_certificates: True
  #   services:
  #     ping_pong_client:
  #       timeout: 300
  #       name: "ping_pong_client"  # Added 'name' key
  #       implementation: 
  #         name: "ping_pong"
  #         type: "iut"
  #       protocol:
  #         name: "minip"
  #         role: "client"
  #         version: "random"
  #         target: "ping_pong_server"  # Docker Compose service name
  #       ports:
  #         - "5000:5000"  # Example port if needed
  #         - "8081:8081"  # Changed to avoid port conflict
  #       generate_new_certificates: True

  #     ping_pong_server:
  #       name: "ping_pong_server"  # Added 'name' key
  #       timeout: 60
  #       implementation: 
  #         type: "iut"
  #         name: "ping_pong"
  #       protocol:
  #         name: "minip"
  #         version: "random"
  #         role: "server"
  #       ports:
  #         - "4443:4443"
  #         - "4987:4987"  #
  #         - "8080:8080"  # Health check endpoint
  #       generate_new_certificates: True

  #   steps:
  #     wait: 300  # seconds to wait during the test

  
