logging:
  level: INFO
  format: "%(asctime)s [%(levelname)s] - %(module)s - %(message)s"
  
paths:
  output_dir: "outputs"
  log_dir: "outputs/logs"
  config_dir: "panther/configs"
  plugin_dir: "panther/plugins"

docker:
  build_docker_image: True
 
tests:
  - name: "QUIC IyvClient-Server Communication Test - Strace"
    description: "Verify that the Picoquic server can communicate with the Ivy-Tester client over Docker Compose network."
    network_environment: 
      type: "docker_compose" 
    execution_environment: 
      - type: "strace"  
    iterations: 1
    should_be_ignore : "should_be_ignore"
    services:
      picoquic_server:
        name: "picoquic_server" 
        timeout: 100
        implementation: 
          name: "picoquic" # parameters are presents in folder plugins/services/implementations/quic/picoquic/config.yaml
          type: "iut"      # plugin is present plugins/services/iut/quic/picoquic
        protocol:          # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "server"
        ports:
          - "4443:4443"
          - "8080:8080"  # Health check endpoint
        generate_new_certificates: True
        should_be_ignore : "should_be_ignore"
          
      ivy_client:
        name: "ivy_client"  # Added 'name' key
        timeout: 100
        implementation: 
          name: "panther_ivy"
          type: "testers" # plugin is present plugins/services/testers/panther_ivy
          test: quic_server_test_stream
        protocol:  # plugin is present plugins/services/iut/quic
          name: "quic"
          version: "rfc9000"
          role: "client"
          target: "picoquic_server"  # Docker Compose service name
        ports:
          - "5000:5000"  
          - "4987:4987"  
          - "8081:8081"  
        generate_new_certificates: True
    steps:
      wait: 100  # seconds to wait during the test
