ARG image

FROM $image:latest

# ADD src/implementations/bgp-implementations/bird /PFV/implementations/bgp-implementations/bird

WORKDIR /PFV/implementations/bgp-implementations/bird/

# https://deploy.equinix.com/developers/docs/metal/bgp/route-bgp-with-bird/

RUN cat >>/etc/network/interfaces <<EOF \
auto lo:0  \
iface lo:0 inet static \
  address 11.0.0.2 \
  netmask 255.255.255.255 \
EOF 

RUN ifup lo:0


RUN apt -y update && apt -y install bird

# RUN autoreconf; ./configure; make; make install