#ivy lang1.7

# https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-26190
# https://github.com/PowerShell/Announcements/issues/58

# Microsoft QUIC Denial of Service Vulnerability
# CVE-2024-26190
# Security Vulnerability

# Released: 12 Mar 2024

# Last updated: 16 Apr 2024
# Assigning CNA:
# Microsoft

# CVE-2024-26190 

# Impact: Denial of Service

# Max Severity: Important
# Weakness:
# CWE-400: Uncontrolled Resource Consumption
# CVSS Source: Microsoft
# CVSS:3.1 7.5 / 6.5
