#ivy lang1.7

# https://my.f5.com/manage/s/article/K000138444

# Published Date: Feb 14, 2024Updated Date: Feb 14, 2024

#     Download Article

# AI Recommended Content

# Final- This article is marked as 'Final' because the security issue described in this article either affected F5 products at one time and was resolved or it never affected F5 products. Unless new information is discovered, F5 will no longer update the article.

# Security Advisory Description

# When NGINX Plus or NGINX OSS are configured to use the HTTP/3 QUIC module, undisclosed requests can cause NGINX worker processes to terminate. (CVE-2024-24989)

# Note: The HTTP/3 QUIC module is not enabled by default and is considered experimental. For more information, refer to Support for QUIC and HTTP/3.

# Impact

# Traffic is disrupted while the NGINX process restarts. This vulnerability allows a remote unauthenticated attacker to cause a denial-of-service (DoS) on the NGINX system. There is no control plane exposure; this is a data plane issue only.

# Security Advisory Status

# F5 Product Development has assigned ID NWA-1884 (NGINX Plus and NGINX OSS) to this vulnerability. This issue has been classified as CWE-476: NULL Pointer Dereference.

# To determine if your product and version have been evaluated for this vulnerability, refer to the Evaluated products box. To determine if your release is known to be vulnerable, the components or features that are affected by the vulnerability, and for information about releases, point releases, or hotfixes that address the vulnerability, refer to the following tables. For more information about security advisory versioning, refer to K51812227: Understanding security advisory versioning.

# Security Advisory Recommended Actions

# If you are running a version listed in the Versions known to be vulnerable column, you can eliminate this vulnerability by installing a version listed in the Fixes introduced in column. If the Fixes introduced in column does not list a version for your branch, then no update candidate currently exists for that branch and F5 recommends that you upgrade to a version with the fix (refer to the tables).

# If the Fixes introduced in column lists a version prior to the one you are running, in the same branch, then your version should have the fix.

# Mitigation

# None. F5 recommends that you disable the HTTP/3 module in the NGINX configuration. For more information, refer to the Module ngx_http_v3_module page.

action launch_cve_2024_24989() = {
    call show_cve_2024_24989;
}

import action show_cve_2024_24989()