include ping_frame 

object ping_frame = {
    ...

    object malicious_frame = {
        variant this of ping_frame = struct {
            data : stream_data
        }
    }
}

object ping_frame = {
    ...
    object malicious_frame = {
        ...
        action handle(f:ping_frame.malicious_frame)

	around handle {
            require f.data.end = 4;
	        ...
            call enqueue_frame(f);
        }
    }
}