#lang ivy1.7


include ping_byte_stream
include collections
include ping_frame
include apt_packet

object packet = {

    ...

    object forged_ping_packet = {
        # Ping ping_frames contain no data, check peers still alive
        variant this of packet = struct {
            payload : ping_frame.arr
        }
        instance idx : unbounded_sequence
        instance arr : array(idx,this) 
    }    
}
