ARG image

FROM $image:latest

# ADD panther/panther_worker/app/implementations/quic-implementations/picoquic-vuln /app/implementations/quic-implementations/picoquic-vuln
# ADD panther/panther_worker/app/implementations/quic-implementations/picotls /app/implementations/quic-implementations/picotls

ENV OPENSSL_INCLUDE_DIR=/usr/include/openssl
WORKDIR /app/implementations/quic-implementations/picotls
RUN git stash
RUN git checkout 5e0f82e184f1ae79de58837819b13ea7ef89b6f1
RUN apt-get install libssl-dev -y
RUN OPENSSL_INCLUDE_DIR="/usr/include/openssl" cmake .
RUN make
RUN make check
WORKDIR /app/implementations/quic-implementations/picoquic-vuln/
RUN git clone https://github.com/private-octopus/picoquic.git .
RUN git checkout 97687415c78f5cae4ea3ac6a7373e369415480ce
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /app

