#lang ivy1.7

# a fake serializer for BGP

object bgp_ser_keepalive = {}

<<< member

    class `bgp_ser_keepalive`;

>>>

<<< impl
    
    class `bgp_ser_keepalive` : public ivy_binary_ser_128 {
        enum {bgp_s_init} state;
        long frame_type;

    public:
        bgp_ser_keepalive() : state(bgp_s_init) {
        }
        virtual void  set(int128_t res) {
            switch (state) {
            case bgp_s_init:
            {
            }
            break;
            default:
            std::cerr << "deser_err 42 "  << "\n";  
            throw deser_err();
            }
        }


        virtual void open_tag(int tag, const std::string &) {
            std::cerr << "deser_err 43 " << tag << "\n";  
            std::cerr << "deser_err 43 " << state << "\n";  
            throw deser_err();
        }

        virtual void open_list_elem() {
        }

        void open_list(int len) {

        }
        void close_list() {
        }
        void close_list_elem() {}

        virtual void close_tag() {
        }

        ~bgp_ser_keepalive(){}
    };

>>>
