#lang ivy1.7

#    BGP Identifier
#       A 4-octet unsigned integer that indicates the BGP Identifier of
#       the sender of BGP messages.  A given BGP speaker sets the value of
#       its BGP Identifier to an IP address assigned to that BGP speaker.
#       The value of the BGP Identifier is determined upon startup and is
#       the same for every local interface and BGP peer.
type bgp_id

# The type `version` represents a protocol version as a 8-bit unsigned number.

type version 

#  This 2-octet unsigned integer indicates the Autonomous System number of the sender.

type as_number

type microseconds
type seconds
type milliseconds

# This 16-octet field is included for compatibility; it MUST be set to all ones.
type marker_id
interpret marker_id -> longbv[1][16][16]

type segmenttype



type prefix
# interpret prefix -> stream_data
