---
version: "3"
services:

  server:
    image: ntap/quant
    expose:
      - 4433/udp
    command: server -i eth0 -t 1 -v4 -d /www -c /tls/quant.crt -k /tls/quant.key

  valve:
    depends_on:
      - server
    image: ntap/qvalve
    expose:
      - 4433/udp
    volumes:
      - ./qvalve-tests:/qvalve-tests:ro
    command: env PYTHONUNBUFFERED=1 qvalve -ra server -r tests/demo.qv

  client:
    depends_on:
      - server
      - valve
    image: ntap/quant
    command: client -v4 -i eth0 https://valve/index.html
