ARG image

FROM $image:latest

ADD pfv/pfv_worker/implementations/quic-implementations/quant-vuln /app/implementations/quic-implementations/quant-vuln

RUN apt remove --fix-missing -y cmake
RUN wget https://github.com/Kitware/CMake/releases/download/v3.12.4/cmake-3.12.4-Linux-x86_64.sh  
RUN chmod +x cmake-3.12.4-Linux-x86_64.sh
RUN mkdir /opt/cmake
RUN bash cmake-3.12.4-Linux-x86_64.sh --skip-license --prefix=/opt/cmake
RUN ln -s /opt/cmake/bin/cmake /usr/local/bin/cmake
RUN cmake --version

WORKDIR /app/implementations/quic-implementations/quant-vuln/
RUN git checkout bf903dd176738e7d00ae925c7e8da9651f09e5cb
RUN git submodule update --init --recursive
COPY src/containers/res/quant/cid.h /app/implementations/quic-implementations/quant-vuln/lib/src/cid.h 
# for 16 bytes max
RUN mkdir Debug 
WORKDIR /app/implementations/quic-implementations/quant-vuln/Debug
RUN cmake ..
RUN make

WORKDIR /app

