ARG image

FROM $image:latest

ADD pfv/pfv_worker/implementations/quic-implementations/picoquic /PFV/implementations/quic-implementations/picoquic

WORKDIR /PFV/implementations/quic-implementations/picoquic/
# RUN git checkout bb67995f2d7c0e577c2c8788313c3b580d3df9a7 # 639c9e685d37e74d357d3dd8599b9dbff90934af
COPY src/containers/res/picoquic/rfc9000/picoquic_internal.h  /PFV/implementations/quic-implementations/picoquic/picoquic/picoquic_internal.h
RUN /usr/bin/cmake --version
RUN /usr/bin/cmake .
RUN make
RUN ./picoquic_ct || true

WORKDIR /PFV
