#lang ivy1.7

include order
include bgp_infer
include file
include bgp_shim
include random_value

parameter speaker_addr : ip.addr = 0x0a000001 # 0x7f000001
parameter speaker_id   : bgp_id = 0x0a000001
parameter speaker_as   : as_number = 1

parameter speaker_impl_addr : ip.addr = 0x0a000003 # 0x7f000001
parameter speaker_impl_id   : bgp_id = 0x0a000003
parameter speaker_impl_as   : as_number = 2

# create a client and server. the client has an instance of TLS

instance bgp_ivy_instance  : bgp_speaker.speaker(speaker_addr,speaker_id,speaker_as)

instance bgp_impl_instance : bgp_speaker.speaker(speaker_impl_addr,speaker_impl_id,speaker_impl_as)
