#lang ivy1.7

include quic_client_test

#   A receiver MUST accept packets containing an
#   outdated frame, such as a MAX_DATA frame carrying a smaller maximum
#   data than one found in an older packet.
# => test where we send packet only with max_data with random value we should be ack for all packet 
#    if good

before frame.max_data.handle(f:frame.max_data,scid:cid,dcid:cid,e:quic_packet_type,seq_num:pkt_num) {
    if _generating {
        require f.pos > 0;
    }
}

export frame.max_streams.handle
export frame.max_stream_data.handle
export frame.max_data.handle
#export frame.stream_blocked.handle
export frame.rst_stream.handle

attribute frame.rst_stream.handle.weight = "0.02"
attribute frame.max_data.handle.weight = "5"


# export frame.connection_close.handle
# attribute frame.connection_close.handle.weight = "0.02"

#export frame.application_close.handle
#attribute frame.application_close.handle.weight = "0.02"

export frame.stop_sending.handle
