"""
ML-Powered Analytics System
Phase 4 implementation of ATLAS Hierarchical Cache Architecture
Advanced pattern recognition, anomaly detection, and predictive analytics
"""

import json
import time
import numpy as np
import statistics
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Any, Optional, Set, Tuple, Union
from dataclasses import dataclass, asdict
from collections import defaultdict, Counter, deque
import threading
import hashlib
import math
import re

try:
    from sklearn.ensemble import IsolationForest
    from sklearn.cluster import DBSCAN
    from sklearn.preprocessing import StandardScaler
    from sklearn.metrics import silhouette_score
    SKLEARN_AVAILABLE = True
except ImportError:
    SKLEARN_AVAILABLE = False

from .hierarchical_cache_manager import HierarchicalCacheManager
from .content_hash_validator import ContentHashValidator
from .language_aware_cache import LanguageAwareSymbolCache, LanguageType
from .performance_analytics import CachePerformanceDashboard
from .cross_project_intelligence import CrossProjectIntelligenceOrchestrator, CodePattern


@dataclass
class MLPattern:
    """ML-discovered code pattern with confidence and complexity scores"""
    pattern_id: str
    pattern_type: str  # 'semantic', 'structural', 'behavioral', 'performance'
    pattern_name: str
    pattern_signature: str
    complexity_score: float  # 0-1, higher = more complex
    confidence_score: float  # 0-1, ML confidence
    semantic_similarity: float  # 0-1, semantic similarity to known patterns
    frequency: int
    projects: List[str]
    files: List[str]
    language: LanguageType
    discovered_at: float
    ml_features: Dict[str, float]  # Feature vector used for discovery
    predicted_usefulness: float  # 0-1, ML prediction of pattern utility


@dataclass
class PerformanceAnomaly:
    """Detected performance anomaly with ML analysis"""
    anomaly_id: str
    anomaly_type: str  # 'response_time', 'memory', 'hit_rate', 'throughput'
    severity: str  # 'critical', 'high', 'medium', 'low'
    detected_at: float
    affected_projects: List[str]
    metric_name: str
    baseline_value: float
    anomalous_value: float
    deviation_score: float  # Standard deviations from normal
    confidence: float  # ML model confidence
    root_cause_analysis: Dict[str, Any]
    suggested_actions: List[str]
    historical_context: Dict[str, Any]


@dataclass
class PredictiveInsight:
    """Predictive insight generated by ML models"""
    insight_id: str
    insight_type: str  # 'performance_degradation', 'cache_overflow', 'pattern_emergence'
    prediction_horizon: str  # 'hours', 'days', 'weeks'
    confidence: float  # 0-1
    predicted_impact: Dict[str, float]
    trigger_conditions: List[str]
    prevention_strategies: List[str]
    generated_at: float
    model_version: str


@dataclass
class CodeQualityAnomaly:
    """Code quality anomaly detected by ML analysis"""
    anomaly_id: str
    file_path: str
    anomaly_type: str  # 'complexity_spike', 'anti_pattern', 'duplication', 'inconsistency'
    severity: str
    description: str
    affected_symbols: List[str]
    quality_metrics: Dict[str, float]
    suggestions: List[str]
    detected_at: float
    confidence: float


class MLPatternRecognition:
    """Advanced ML-powered pattern recognition system"""
    
    def __init__(self, cache_manager: HierarchicalCacheManager,
                 symbol_cache: LanguageAwareSymbolCache):
        self.cache_manager = cache_manager
        self.symbol_cache = symbol_cache
        self.ml_patterns_cache_type = "ml_patterns"
        self.feature_cache_type = "ml_features"
        self._lock = threading.Lock()
        
        # Initialize ML components if available
        self.ml_available = SKLEARN_AVAILABLE
        if self.ml_available:
            self.isolation_forest = IsolationForest(contamination=0.1, random_state=42)
            self.clustering_model = DBSCAN(eps=0.3, min_samples=2)
            self.scaler = StandardScaler()
        
        # Pattern analysis components
        self.semantic_analyzer = SemanticPatternAnalyzer()
        self.structural_analyzer = StructuralPatternAnalyzer()
        self.behavioral_analyzer = BehavioralPatternAnalyzer()
    
    def discover_ml_patterns(self, project_id: str, file_paths: List[str]) -> List[MLPattern]:
        """Discover patterns using advanced ML techniques"""
        patterns = []
        
        # Extract features from code
        feature_matrix, file_metadata = self._extract_ml_features(file_paths)
        
        if not feature_matrix:
            return patterns
        
        # Semantic pattern discovery
        semantic_patterns = self.semantic_analyzer.discover_patterns(
            feature_matrix, file_metadata, project_id
        )
        patterns.extend(semantic_patterns)
        
        # Structural pattern discovery
        structural_patterns = self.structural_analyzer.discover_patterns(
            feature_matrix, file_metadata, project_id
        )
        patterns.extend(structural_patterns)
        
        # Behavioral pattern discovery
        behavioral_patterns = self.behavioral_analyzer.discover_patterns(
            feature_matrix, file_metadata, project_id
        )
        patterns.extend(behavioral_patterns)
        
        # ML-based clustering for unknown patterns
        if self.ml_available:
            ml_patterns = self._discover_ml_clusters(feature_matrix, file_metadata, project_id)
            patterns.extend(ml_patterns)
        
        # Score and filter patterns
        patterns = self._score_and_filter_patterns(patterns)
        
        # Cache discovered patterns
        self._cache_ml_patterns(project_id, patterns)
        
        return patterns
    
    def predict_pattern_evolution(self, pattern: MLPattern) -> Dict[str, Any]:
        """Predict how a pattern might evolve based on ML analysis"""
        evolution_prediction = {
            "pattern_id": pattern.pattern_id,
            "predicted_growth_rate": self._predict_growth_rate(pattern),
            "estimated_adoption_timeline": self._estimate_adoption_timeline(pattern),
            "quality_trend": self._predict_quality_trend(pattern),
            "risk_factors": self._identify_risk_factors(pattern),
            "optimization_opportunities": self._identify_optimization_opportunities(pattern)
        }
        
        return evolution_prediction
    
    def _extract_ml_features(self, file_paths: List[str]) -> Tuple[List[List[float]], List[Dict]]:
        """Extract ML features from code files"""
        feature_matrix = []
        file_metadata = []
        
        for file_path in file_paths:
            symbol_map = self.symbol_cache.analyze_file(file_path)
            if not symbol_map:
                continue
            
            features = []
            metadata = {"file_path": file_path, "language": symbol_map.language}
            
            # Basic code metrics
            features.extend([
                len(symbol_map.symbols),  # Symbol count
                len(symbol_map.imports),  # Import count
                len([s for s in symbol_map.symbols if s.symbol_type == "function"]),  # Function count
                len([s for s in symbol_map.symbols if s.symbol_type == "class"]),  # Class count
                len([s for s in symbol_map.symbols if s.symbol_type == "variable"]),  # Variable count
            ])
            
            # Complexity metrics
            avg_func_params = statistics.mean([
                len(s.parameters) for s in symbol_map.symbols 
                if s.symbol_type == "function" and s.parameters
            ]) if any(s.symbol_type == "function" for s in symbol_map.symbols) else 0
            
            features.extend([
                avg_func_params,
                len([s for s in symbol_map.symbols if len(s.parameters) > 5]),  # Complex functions
                len([s for s in symbol_map.symbols if s.docstring]),  # Documented symbols
            ])
            
            # Naming pattern features
            naming_features = self._extract_naming_features(symbol_map.symbols)
            features.extend(naming_features)
            
            # Structure features
            structure_features = self._extract_structure_features(symbol_map)
            features.extend(structure_features)
            
            feature_matrix.append(features)
            file_metadata.append(metadata)
        
        return feature_matrix, file_metadata
    
    def _extract_naming_features(self, symbols) -> List[float]:
        """Extract naming pattern features"""
        if not symbols:
            return [0.0] * 8
        
        names = [s.name for s in symbols]
        
        # Naming convention consistency
        snake_case_count = sum(1 for name in names if '_' in name and name.islower())
        camel_case_count = sum(1 for name in names if any(c.isupper() for c in name[1:]) and '_' not in name)
        
        # Average name length
        avg_name_length = statistics.mean([len(name) for name in names]) if names else 0
        
        # Abbreviation usage
        abbrev_count = sum(1 for name in names if len(name) <= 3 or any(char.isupper() for char in name))
        
        # Verb-noun pattern in functions
        verb_pattern_count = sum(1 for s in symbols 
                               if s.symbol_type == "function" and 
                               any(verb in s.name.lower() for verb in ['get', 'set', 'create', 'update', 'delete']))
        
        total_symbols = len(symbols)
        
        return [
            snake_case_count / total_symbols,
            camel_case_count / total_symbols,
            avg_name_length / 20.0,  # Normalize
            abbrev_count / total_symbols,
            verb_pattern_count / max(1, len([s for s in symbols if s.symbol_type == "function"])),
            len(set(names)) / total_symbols,  # Name uniqueness
            sum(len(name.split('_')) for name in names) / total_symbols,  # Compound names
            sum(1 for name in names if name.startswith('_')) / total_symbols  # Private indicators
        ]
    
    def _extract_structure_features(self, symbol_map) -> List[float]:
        """Extract structural features"""
        if not symbol_map.symbols:
            return [0.0] * 6
        
        # Inheritance patterns
        class_symbols = [s for s in symbol_map.symbols if s.symbol_type == "class"]
        inheritance_depth = len([s for s in class_symbols if s.parameters])  # Rough proxy
        
        # Import patterns
        import_diversity = len(set(imp.module for imp in symbol_map.imports))
        relative_imports = sum(1 for imp in symbol_map.imports if imp.module.startswith('.'))
        
        # Function organization
        nested_functions = sum(1 for s in symbol_map.symbols 
                             if s.symbol_type == "function" and '.' in s.name)
        
        # Code density
        total_lines = max(s.line_end for s in symbol_map.symbols) if symbol_map.symbols else 1
        symbol_density = len(symbol_map.symbols) / total_lines
        
        return [
            inheritance_depth / max(1, len(class_symbols)),
            import_diversity / max(1, len(symbol_map.imports)),
            relative_imports / max(1, len(symbol_map.imports)),
            nested_functions / max(1, len([s for s in symbol_map.symbols if s.symbol_type == "function"])),
            symbol_density,
            len(symbol_map.exports) / max(1, len(symbol_map.symbols))
        ]
    
    def _discover_ml_clusters(self, feature_matrix: List[List[float]], 
                            file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Discover patterns using ML clustering"""
        if not self.ml_available or len(feature_matrix) < 3:
            return []
        
        # Normalize features
        features_array = np.array(feature_matrix)
        normalized_features = self.scaler.fit_transform(features_array)
        
        # Perform clustering
        cluster_labels = self.clustering_model.fit_predict(normalized_features)
        
        patterns = []
        for cluster_id in set(cluster_labels):
            if cluster_id == -1:  # Noise cluster
                continue
            
            cluster_indices = [i for i, label in enumerate(cluster_labels) if label == cluster_id]
            if len(cluster_indices) < 2:  # Need at least 2 files for a pattern
                continue
            
            # Analyze cluster
            cluster_features = [feature_matrix[i] for i in cluster_indices]
            cluster_files = [file_metadata[i]["file_path"] for i in cluster_indices]
            
            # Calculate pattern characteristics
            pattern = self._create_ml_pattern_from_cluster(
                cluster_id, cluster_features, cluster_files, project_id
            )
            
            if pattern:
                patterns.append(pattern)
        
        return patterns
    
    def _create_ml_pattern_from_cluster(self, cluster_id: int, cluster_features: List[List[float]],
                                       cluster_files: List[str], project_id: str) -> Optional[MLPattern]:
        """Create ML pattern from clustering results"""
        if not cluster_features:
            return None
        
        # Calculate cluster centroid
        centroid = [statistics.mean(feature_values) for feature_values in zip(*cluster_features)]
        
        # Calculate pattern characteristics
        pattern_signature = self._generate_pattern_signature(centroid)
        complexity_score = self._calculate_complexity_score(centroid)
        confidence_score = self._calculate_cluster_confidence(cluster_features)
        
        return MLPattern(
            pattern_id=f"ml_cluster_{cluster_id}_{int(time.time())}",
            pattern_type="behavioral",
            pattern_name=f"ML_Discovered_Pattern_{cluster_id}",
            pattern_signature=pattern_signature,
            complexity_score=complexity_score,
            confidence_score=confidence_score,
            semantic_similarity=self._calculate_semantic_similarity(centroid),
            frequency=len(cluster_files),
            projects=[project_id],
            files=cluster_files,
            language=LanguageType.UNKNOWN,
            discovered_at=time.time(),
            ml_features=dict(enumerate(centroid)),
            predicted_usefulness=self._predict_usefulness(centroid, len(cluster_files))
        )
    
    def _generate_pattern_signature(self, centroid: List[float]) -> str:
        """Generate human-readable pattern signature from feature centroid"""
        # Analyze dominant features
        dominant_features = []
        
        if centroid[0] > 5:  # Many symbols
            dominant_features.append("high_symbol_density")
        if centroid[1] > 3:  # Many imports
            dominant_features.append("import_heavy")
        if centroid[2] > 2:  # Many functions
            dominant_features.append("function_oriented")
        if centroid[3] > 1:  # Many classes
            dominant_features.append("class_based")
        
        return "_".join(dominant_features) if dominant_features else "generic_pattern"
    
    def _calculate_complexity_score(self, centroid: List[float]) -> float:
        """Calculate complexity score from feature centroid"""
        # Weight different features for complexity
        complexity_weights = [0.1, 0.1, 0.2, 0.3, 0.1, 0.2]  # Weights for each feature group
        
        weighted_sum = sum(centroid[i] * complexity_weights[i % len(complexity_weights)] 
                          for i in range(min(len(centroid), len(complexity_weights))))
        
        return min(weighted_sum / 10.0, 1.0)  # Normalize to 0-1
    
    def _calculate_cluster_confidence(self, cluster_features: List[List[float]]) -> float:
        """Calculate confidence based on cluster cohesion"""
        if len(cluster_features) < 2:
            return 0.0
        
        # Calculate variance within cluster
        variances = []
        for feature_idx in range(len(cluster_features[0])):
            feature_values = [features[feature_idx] for features in cluster_features]
            if len(set(feature_values)) > 1:
                variances.append(statistics.variance(feature_values))
            else:
                variances.append(0.0)
        
        # Lower variance = higher confidence
        avg_variance = statistics.mean(variances) if variances else 0
        confidence = max(0.0, 1.0 - (avg_variance / 10.0))  # Normalize
        
        return confidence
    
    def _calculate_semantic_similarity(self, centroid: List[float]) -> float:
        """Calculate semantic similarity to known patterns"""
        # This would compare against known good patterns
        # For now, use a heuristic based on feature balance
        
        feature_balance = 1.0 - statistics.stdev(centroid[:5]) if len(centroid) >= 5 else 0.5
        return min(feature_balance, 1.0)
    
    def _predict_usefulness(self, centroid: List[float], frequency: int) -> float:
        """Predict how useful this pattern might be"""
        # Combine multiple factors
        frequency_score = min(frequency / 10.0, 1.0)
        complexity_balance = 1.0 - abs(0.5 - self._calculate_complexity_score(centroid))
        feature_richness = min(len([f for f in centroid if f > 0.1]) / 10.0, 1.0)
        
        return (frequency_score * 0.4 + complexity_balance * 0.3 + feature_richness * 0.3)
    
    def _score_and_filter_patterns(self, patterns: List[MLPattern]) -> List[MLPattern]:
        """Score and filter patterns based on quality criteria"""
        scored_patterns = []
        
        for pattern in patterns:
            # Calculate overall quality score
            quality_score = (
                pattern.confidence_score * 0.3 +
                pattern.predicted_usefulness * 0.3 +
                pattern.semantic_similarity * 0.2 +
                min(pattern.frequency / 5.0, 1.0) * 0.2
            )
            
            # Filter low-quality patterns
            if quality_score > 0.5 and pattern.frequency >= 2:
                scored_patterns.append(pattern)
        
        # Sort by quality score
        return sorted(scored_patterns, 
                     key=lambda p: p.confidence_score * p.predicted_usefulness, 
                     reverse=True)
    
    def _cache_ml_patterns(self, project_id: str, patterns: List[MLPattern]):
        """Cache discovered ML patterns"""
        patterns_data = [asdict(pattern) for pattern in patterns]
        cache_key = f"ml_patterns_{project_id}"
        self.cache_manager.set_cache(
            self.ml_patterns_cache_type,
            cache_key,
            patterns_data,
            cache_level="global"
        )
    
    def _predict_growth_rate(self, pattern: MLPattern) -> Dict[str, float]:
        """Predict pattern growth rate"""
        base_rate = pattern.frequency * 0.1
        complexity_factor = 1.0 - pattern.complexity_score  # Simpler patterns grow faster
        usefulness_factor = pattern.predicted_usefulness
        
        return {
            "weekly_growth_rate": base_rate * complexity_factor * usefulness_factor,
            "confidence": pattern.confidence_score
        }
    
    def _estimate_adoption_timeline(self, pattern: MLPattern) -> Dict[str, str]:
        """Estimate pattern adoption timeline"""
        usefulness = pattern.predicted_usefulness
        complexity = pattern.complexity_score
        
        if usefulness > 0.8 and complexity < 0.3:
            timeline = "1-2 weeks"
        elif usefulness > 0.6 and complexity < 0.5:
            timeline = "1-2 months"
        elif usefulness > 0.4:
            timeline = "3-6 months"
        else:
            timeline = "6+ months or unlikely"
        
        return {
            "estimated_timeline": timeline,
            "confidence": min(pattern.confidence_score * pattern.predicted_usefulness, 1.0)
        }
    
    def _predict_quality_trend(self, pattern: MLPattern) -> Dict[str, Any]:
        """Predict quality trend for pattern"""
        return {
            "trend": "improving" if pattern.semantic_similarity > 0.7 else "stable",
            "quality_score": pattern.semantic_similarity * pattern.confidence_score,
            "risk_level": "low" if pattern.complexity_score < 0.5 else "medium"
        }
    
    def _identify_risk_factors(self, pattern: MLPattern) -> List[str]:
        """Identify risk factors for pattern adoption"""
        risks = []
        
        if pattern.complexity_score > 0.7:
            risks.append("High complexity may hinder adoption")
        if pattern.frequency < 3:
            risks.append("Low frequency indicates limited validation")
        if pattern.confidence_score < 0.6:
            risks.append("Low ML confidence in pattern validity")
        if pattern.predicted_usefulness < 0.5:
            risks.append("Uncertain practical value")
        
        return risks
    
    def _identify_optimization_opportunities(self, pattern: MLPattern) -> List[str]:
        """Identify optimization opportunities"""
        opportunities = []
        
        if pattern.complexity_score > 0.5:
            opportunities.append("Simplify pattern structure for better adoption")
        if pattern.semantic_similarity < 0.7:
            opportunities.append("Improve semantic consistency with established patterns")
        if pattern.frequency > 5 and pattern.predicted_usefulness > 0.7:
            opportunities.append("High-value pattern ready for widespread promotion")
        
        return opportunities


class SemanticPatternAnalyzer:
    """Analyzes semantic patterns in code"""
    
    def discover_patterns(self, feature_matrix: List[List[float]], 
                         file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Discover semantic patterns"""
        patterns = []
        
        # Group files by semantic similarity
        semantic_groups = self._group_by_semantic_similarity(feature_matrix, file_metadata)
        
        for group_id, group_files in semantic_groups.items():
            if len(group_files) >= 2:
                pattern = self._create_semantic_pattern(group_id, group_files, project_id)
                if pattern:
                    patterns.append(pattern)
        
        return patterns
    
    def _group_by_semantic_similarity(self, feature_matrix: List[List[float]], 
                                    file_metadata: List[Dict]) -> Dict[str, List[Dict]]:
        """Group files by semantic similarity"""
        groups = defaultdict(list)
        
        # Simple semantic grouping based on naming patterns and structure
        for i, metadata in enumerate(file_metadata):
            file_path = metadata["file_path"]
            file_name = Path(file_path).stem
            
            # Extract semantic indicators
            if 'test' in file_name.lower():
                semantic_key = "test_files"
            elif 'util' in file_name.lower() or 'helper' in file_name.lower():
                semantic_key = "utility_files"
            elif 'config' in file_name.lower():
                semantic_key = "configuration_files"
            elif 'model' in file_name.lower():
                semantic_key = "model_files"
            else:
                semantic_key = "general_files"
            
            groups[semantic_key].append({
                "metadata": metadata,
                "features": feature_matrix[i] if i < len(feature_matrix) else []
            })
        
        return groups
    
    def _create_semantic_pattern(self, group_id: str, group_files: List[Dict], 
                               project_id: str) -> Optional[MLPattern]:
        """Create semantic pattern from grouped files"""
        if not group_files:
            return None
        
        files = [gf["metadata"]["file_path"] for gf in group_files]
        features = [gf["features"] for gf in group_files if gf["features"]]
        
        if not features:
            return None
        
        # Calculate semantic characteristics
        avg_features = [statistics.mean(feature_values) for feature_values in zip(*features)]
        
        return MLPattern(
            pattern_id=f"semantic_{group_id}_{int(time.time())}",
            pattern_type="semantic",
            pattern_name=f"Semantic_{group_id.replace('_', ' ').title()}",
            pattern_signature=group_id,
            complexity_score=self._calculate_semantic_complexity(avg_features),
            confidence_score=min(len(group_files) / 5.0, 1.0),
            semantic_similarity=0.8,  # High since grouped semantically
            frequency=len(group_files),
            projects=[project_id],
            files=files,
            language=LanguageType.UNKNOWN,
            discovered_at=time.time(),
            ml_features=dict(enumerate(avg_features)),
            predicted_usefulness=self._predict_semantic_usefulness(group_id, len(group_files))
        )
    
    def _calculate_semantic_complexity(self, features: List[float]) -> float:
        """Calculate complexity for semantic patterns"""
        return min(statistics.mean(features[:5]) / 5.0, 1.0) if features else 0.5
    
    def _predict_semantic_usefulness(self, group_id: str, frequency: int) -> float:
        """Predict usefulness of semantic pattern"""
        usefulness_map = {
            "test_files": 0.9,
            "utility_files": 0.8,
            "configuration_files": 0.7,
            "model_files": 0.8,
            "general_files": 0.5
        }
        
        base_usefulness = usefulness_map.get(group_id, 0.5)
        frequency_bonus = min(frequency / 10.0, 0.2)
        
        return min(base_usefulness + frequency_bonus, 1.0)


class StructuralPatternAnalyzer:
    """Analyzes structural patterns in code"""
    
    def discover_patterns(self, feature_matrix: List[List[float]], 
                         file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Discover structural patterns"""
        patterns = []
        
        # Analyze class hierarchies
        hierarchy_patterns = self._analyze_class_hierarchies(feature_matrix, file_metadata, project_id)
        patterns.extend(hierarchy_patterns)
        
        # Analyze module organization
        module_patterns = self._analyze_module_organization(feature_matrix, file_metadata, project_id)
        patterns.extend(module_patterns)
        
        return patterns
    
    def _analyze_class_hierarchies(self, feature_matrix: List[List[float]], 
                                 file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Analyze class hierarchy patterns"""
        # Implementation would analyze class structures
        return []
    
    def _analyze_module_organization(self, feature_matrix: List[List[float]], 
                                   file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Analyze module organization patterns"""
        # Implementation would analyze module structures
        return []


class BehavioralPatternAnalyzer:
    """Analyzes behavioral patterns in code"""
    
    def discover_patterns(self, feature_matrix: List[List[float]], 
                         file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Discover behavioral patterns"""
        patterns = []
        
        # Analyze function usage patterns
        usage_patterns = self._analyze_function_usage(feature_matrix, file_metadata, project_id)
        patterns.extend(usage_patterns)
        
        return patterns
    
    def _analyze_function_usage(self, feature_matrix: List[List[float]], 
                              file_metadata: List[Dict], project_id: str) -> List[MLPattern]:
        """Analyze function usage patterns"""
        # Implementation would analyze function call patterns
        return []