#ivy lang1.7 

# Stage 6: Exfiltrate Data

# When hackers discover valuable information, it's transferred through the backdoors established in stage 3 and into their servers. This usually transpires alongside legitimate network processes to mitigate suspicious network activity spikes.

# If there's a risk of these transfers being intercepted by security teams, APT hackers could deploy white noise tactics like DDoS attacks to divert attention away from exfiltration processes.

# White noise attacks are also deployed to distract security teams before a deeper level of the network is compromised (see figure 4 - cyclical attack lifecycle).

action start_exfiltration() = {

}

action stop_exfiltration() = {

}

action exfiltration() = {
    call start_exfiltration();

    call stop_exfiltration();
}

action eavedrop() = {

}

action covert_channel() = {

}