#ivy lang1.7 

# Infiltration: After gathering enough information about the target environment 
# and its vulnerabilities, attackers deploy customized malware or use other attack
# vectors like spear-phishing emails to gain unauthorized access to the system.

# Stage 2: Gain Access

# After potential entry points have been detected, hackers then attempt exploitation to gain network access.

# This process is usually an orchestrated attack targeting multiple attack vectors within quick succession.

# The breach tactics that make a regular appearance in an APT attackers toolkit include:

#     Spear phishing emails - Seemingly innocuous emails that include infected links to credential-stealing malware. These threats are also known as Spear-Phishing Attacks.
#     Zero-Day Exploits - Software vulnerabilities that have not been addressed with security patches.
#     Social Engineering - Tricking victims into divulging sensitive credentials either via a telephone call or digitally (online chat, email, etc).