#ivy lang1.7 

# Stage 3: Establish a Foothold

# After breaching an IT ecosystem, cybercriminals then deploy trojan malware that establishes a series of backdoor connections to criminal servers (command and control servers) to facilitate the exfiltration of sensitive data.

# Once these backdoors are established, a persistent presence is achieved.

# Learn more about data exfiltration.

action start_c2_communication() = {

}

action stop_c2_communication() = {

}

action c2_communication() = {
    call start_c2_communication();
    
    call stop_c2_communication();
}